### ISSUE TITLE
Linker error with RiderLink

### ISSUE THREAD

**Issue by vamidi** [JetBrains/UnrealLink#10]
I recently downloaded Rider for UE4 and left the settings to default and pressed attach to debugger. After that I received this linker message

https://gyazo.com/686120d01d0dd974699450d4fef4efc0

I am using UE4 4.23

[EDIT]
Fixed when I downloaded 2020.1.7

**Comment by matt-harp** [comment]
Hello, I'm having the same problem as you were, but I cannot determine the fix. Would you mind detailing what you did to resolve this?

**Comment by DecoyRS** [comment]
I'm doing massive overhaul of C++ part of plugin and checking for these errors. I hope next version will solve these

**Comment by vamidi** [comment]
@matt-harp, You need to go to plugins and see if you are indeed on RiderLink 2020.1.4, that was the one installed when I got Rider public preview. That isn't the one you need you need to download the latest here on the [Release page](https://github.com/JetBrains/UnrealLink/releases) and then in Rider install plugin from disk. load the jar file and you are on the latest version. That should fix the compile issue.

**Comment by DecoyRS** [comment]
One more thing, after installing plugin to Rider, you'll need to trigger "Install plugin to Unreal" if you don't have "auto-update RiderLink plugin" checkbox enabled.

**Comment by DecoyRS** [comment]
I've been able to reproduce this problem. It happens when you try to build in non-unity mode. Working on this

**Comment by vamidi** [comment]
So it could happen in every version? When I updated the plugin it disabled the unity mode?

**Comment by DecoyRS** [comment]
Unity build is enabled by default. The problem might be that in your case the order of included cpp files for unity build has luckily resolved in good combination (as well as for me).

**Comment by vamidi** [comment]
could it be the build configuration with `<bUseUnityBuild>false</bUseUnityBuild>`

**Comment by DecoyRS** [comment]
yes, this one exactly is disabling Unity. Enabling it will resolve the problem. Although I've got a fix ready and it'll be available in next release

**Comment by vamidi** [comment]
Great alright I will leave you to it! good luck!

**Comment by abelrguez** [comment]
I implemented the fix by DecoyRS ([73741ac](https://github.com/JetBrains/UnrealLink/commit/73741ac20c686e29df5ba9671d2247cf17219bd8)) by hand and it worked fine for me.

**Comment by DecoyRS** [comment]
Fixed in branch, will be available in next release
