### ISSUE TITLE
UnrealBuildTools [MSB4057] The target does not exist in the project!

### ISSUE THREAD

**Issue by asc-arash** [JetBrains/UnrealLink#105]
HI. Yesterday I performed a clean install of Windows 10 iso file (21h1 19043.985) and then downloaded Unreal Engine v4.25.4 source from Github and compiled it with Visual Studio to get the binaries and all.

After that, I installed Rider for Unreal v2021.1.1, launched UE4 and selected Rider in the Editor Preferences for the default Source Code and opened a C++ class which fired up Rider. After caching and installing Rider Link, I tried to Build/Run the project but it gives me this error over and over.

"UnrealBuildTools [MSB4057] The target does not exist in the project!"

The interesting part is when I open the .uproject file of the project with Rider, it works. but when I open a class from within the Unreal  or open a .sln file, it gives me the error.
----------------------------------------------------
I can't even create a C++ class from the engine and it gives me RiderLink error.

Build Error:
![00](https://user-images.githubusercontent.com/38420895/120078279-f6ff1500-c0c3-11eb-946a-d6f4557a7ac7.jpg)
![03](https://user-images.githubusercontent.com/38420895/120078300-17c76a80-c0c4-11eb-9691-7c6bd4410a5b.jpg)

RiderLink Error:
![04](https://user-images.githubusercontent.com/38420895/120078285-02524080-c0c4-11eb-84c0-0e06d5fa9919.jpg)
![05](https://user-images.githubusercontent.com/38420895/120078288-05e5c780-c0c4-11eb-8cda-cfe4c55a672a.jpg)

**Comment by DecoyRS** [comment]
Hello @asc-arash
This is a bug in MSBuild bundled with the latest version of Visual Studio 2019, more specifically version 16.10 from 25th of May.
https://developercommunity.visualstudio.com/t/MSBuild-fails-to-build-single-project-fr/1434817?space=8&q=MSBuild+16.10
You can either downgrade your Visual Studio to version 16.9 from here: https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release
or wait for the patch from Microsoft mentioned here: https://github.com/dotnet/msbuild/issues/6499#issuecomment-850551187

**Comment by asc-arash** [comment]
@DecoyRS 
Thank you so much for your response. I was suspicious about that and I was downloading VS2017 to try it, and suddenly saw your reply.
I use the Community Edition of Visual Studio which unfortunately is not available to download on the page link you provided. So I guess I use VS2017 or Visual Assist while waiting for VS2019 update.

**Comment by DecoyRS** [comment]
@asc-arash
No problem! 
as stated on SO, these installers should be able to install community edition as well
https://stackoverflow.com/questions/63304331/how-do-i-install-a-previous-version-of-visual-studio-2019-community
