### ISSUE TITLE
RiderLink Build on UE5

### ISSUE THREAD

**Issue by pixelpixi** [JetBrains/UnrealLink#109]
I am unable to build RiderLink under UE5. It's complaining that std::c++17 is required. Is there a way I can enable that build option for compiling the riderlink plugin?

[RiderLinkLog.txt](https://github.com/JetBrains/UnrealLink/files/6650210/RiderLinkLog.txt)

**Comment by DecoyRS** [comment]
Hi @pixelpixi 
A fix is on the way. As a workaround, you can add 
`PublicDefinitions.Add("_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS");` to RD.Build.cs file

**Comment by pixelpixi** [comment]
Ah great. Thank you!

**Comment by pixelpixi** [comment]
I tried the workaround but still couldn't compile it. (I found and edited the file inside of C:\Program Files\JetBrains\Rider for Unreal Engine 2020.2\plugins\UnrealLink\EditorPlugin\RiderLink.zip)

Please let me know if there is a different place or if there is something else I can do to get it compiled.

Thanks.

**Comment by ChunkinFlubber** [comment]
Looks like the new update with a fix for building ue5-main just went live on the rider marketplace, so hopefully that should fix it.

**Comment by pixelpixi** [comment]
That did fix it! Thanks.
