### ISSUE TITLE
Feature Request: Linux/Mac compatibility

### ISSUE THREAD

**Issue by ericwomer** [JetBrains/UnrealLink#11]
Currently not compatible with the Linux or Mac Rider and UnrealEngine code pipeline.

**Comment by xxvunborn** [comment]
Any update on this?

**Comment by DecoyRS** [comment]
Short answer: Rider for Unreal Engine officially is not working on mac and linux, thus UnreaLink is not supporting these platforms.
Long answer: Rider 4UE is already working on netcore on macOS and linux, but VC++ and vcxproj are not available on these platforms. After adding support for clang toolchain to Rider, and finilazing work on project model based on uproject, we'll be avable to say "we have linux/mac compatibility".
How to get notification? Everyone who got Rider 4UE will get notification in email with update. And we'll be *really* vocal when we'll have these things working)

**Comment by DecoyRS** [comment]
Resolved in 7a2fd135b94c28d2c82a32e51f597e280d39bac0
NB: This issues is about UnrealLink/RiderLink plugins. They are working on MacOS and Linux right now. "Rider for Unreal Engine" at this very moment is not available for Linux and MacOS for users. Stay tuned :)

**Comment by DecoyRS** [comment]
For anyone interested in R4UE on Mac and Linux, wath this issue:
https://youtrack.jetbrains.com/issue/RIDER-43518
