### ISSUE TITLE
"RiderLink plugin was designed for build 4.26.0" message

### ISSUE THREAD

**Issue by jorgenpt** [JetBrains/UnrealLink#112]
When I boot up our 4.26.2 (latest stable release of 4.26) with the latest RiderLink/Rider, I get a popup that tells me the plugin isn't designed for my engine version:

![image](https://user-images.githubusercontent.com/21258/122610248-2904f680-d034-11eb-8910-d62f59dd5967.png)

If I choose yes, it loads fine, but it's annoying that it requires manual intervention to start the editor. This seems to be because Engine\Plugins\Developer\RiderLink\RiderLink.uplugin has an EngineVersion specification for 4.26:

```json
{
  "EngineVersion": "4.26.0"
}
```

I don't see that in the RiderLink.uplugin.template in this project, so I'm not sure what's adding it.

UnrealLink IDE plugin version 2021.1.9 and RiderLink UE4 plugin version 2021.1.9 as well.

Rider version info:
```
Rider for Unreal Engine 2021.1.2
Build #RDCPPP-211.7442.37, built on May 28, 2021
Licensed to Joergen Tjernoe
Subscription is active until November 30, 2021.
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 2500M
Cores: 16
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, vcs.enable.add.ignored.directories.to.exclude=false, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: com.microsoft.vso.idea (1.161.1), org.toml.lang (0.2.148.3911-211), unreal-link (2021.1.9), org.rust.lang (0.4.148.3911-211)
```

**Comment by DecoyRS** [comment]
Fixed with https://github.com/JetBrains/UnrealLink/commit/fc114f2262e1552521937fb7877755697d4fb750
Will be available in the next build
