### ISSUE TITLE
Failed to build RiderLink plugin

### ISSUE THREAD

**Issue by cloudxunuo** [JetBrains/UnrealLink#114]
Automation.ParseCommandLine: Parsing command line: BuildPlugin -Plugin=C:\Users\garraxu\AppData\Local\Temp\UnrealLink\Vinekyz\RiderLink.uplugin -Package=C:\Users\garraxu\AppData\Local\Temp\UnrealLink\Fuxufoc -Rocket -WaitMutex -compile
Automation.Process: Setting up command environment.
InternalUtils.SafeFileExists: SafeFileExists D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationTool.EXE=True
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_LOCAL_ROOT=
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_LOCAL_ROOT=
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_EngineSavedFolder=
CommandUtils.SetEnvVar: SetEnvVar uebp_EngineSavedFolder=D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_EngineSavedFolder=D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_CSVFile=
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_LogFolder=
CommandUtils.SetEnvVar: SetEnvVar uebp_LogFolder=D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\Log.txt
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_FinalLogFolder=
CommandUtils.SetEnvVar: SetEnvVar uebp_FinalLogFolder=D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs
InternalUtils.SafeFileExists: SafeFileExists C:\WINDOWS\system32\robocopy.exe=True
InternalUtils.SafeFileExists: SafeFileExists C:\WINDOWS\system32\mount.exe=False
InternalUtils.SafeFileExists: SafeFileExists C:\WINDOWS\Sysnative\mount.exe=False
InternalUtils.SafeFileExists: SafeFileExists C:\WINDOWS\system32\cmd.exe=True
CommandUtils.SetEnvVar: SetEnvVar MallocNanoZone=0
InternalUtils.GetEnvironmentVariable: GetEnvironmentVariable uebp_UATChildInstance=0
WindowsPlatform.FindVisualStudioInstallations: Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional (Product=Microsoft.VisualStudio.Product.Professional, Version=16.9.31313.79)
MacPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.MacPlatformSDK using manually installed SDK
TVOSPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.IOSPlatformSDK using manually installed SDK
AndroidPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.AndroidPlatformSDK has no valid SDK
HoloLensPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.HoloLensPlatformSDK using manually installed SDK
IOSPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.IOSPlatformSDK using manually installed SDK
LinuxPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.LinuxPlatformSDK has no valid SDK
LuminSDKVersionHelper.HasAnySDK: *** Unable to determine MLSDK location ***
LuminSDKVersionHelper.HasAnySDK: *** Unable to determine MLSDK location ***
LuminPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.LuminPlatformSDK has no valid SDK
WindowsPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.WindowsPlatformSDK using manually installed SDK
ScriptCompiler.FindAndCompileAllScripts: Found 16 project files in 0.211s
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AllDesktop\AllDesktop.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Android\Android.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\AutomationUtils.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\BuildGraph\BuildGraph.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Gauntlet\Gauntlet.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\IOS\IOS.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Linux\Linux.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Localization\Localization.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Lumin\Lumin.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Mac\Mac.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\OneSkyLocalization\OneSkyLocalization.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\TVOS\TVOS.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Win\Win.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\XLocLocalization\XLocLocalization.Automation.csproj
ScriptCompiler.FindAndCompileAllScripts: Parsed project files in 0.072s
ScriptCompiler.CompileAutomationProjects: Dependencies are out of date. Compiling scripts....
InternalUtils.SafeDeleteDirectory: SafeDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AutomationScripts.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AutomationScripts.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AWSSDK.Core.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AWSSDK.S3.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\BuildGraph.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\BuildGraph.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\BuildGraph.Automation.xml
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Gauntlet.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Gauntlet.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Localization.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Localization.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Magick.NET-Q16-HDRI-AnyCPU.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Newtonsoft.Json.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Newtonsoft.Json.xml
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\OneSkyLocalization.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\OneSkyLocalization.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Win.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Win.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\XLocLocalization.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\XLocLocalization.Automation.pdb
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AllDesktop
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AllDesktop\AllDesktop.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AllDesktop\AllDesktop.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\AllDesktop
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android\Android.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android\Android.Automation.pdb
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android\Ionic.Zip.Reduced.dll
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Android
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\HoloLens
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\HoloLens
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\IOS
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\IOS\IOS.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\IOS\IOS.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\IOS
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Linux
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Linux\Linux.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Linux\Linux.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Linux
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Lumin
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Lumin\Lumin.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Lumin\Lumin.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Lumin
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Mac
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Mac\Mac.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Mac\Mac.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\Mac
InternalUtils.RecursivelyDeleteDirectory: RecursivelyDeleteDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\TVOS
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\TVOS\TVOS.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\TVOS\TVOS.Automation.pdb
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts\TVOS
InternalUtils.SafeDeleteEmptyDirectory: SafeDeleteEmptyDirectory D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationScripts
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationUtils.Automation.dll
InternalUtils.SafeDeleteFile: SafeDeleteFile D:\UGit\UnrealEngine\Engine\Binaries\DotNET\AutomationUtils.Automation.pdb
ProcessResult.StdOut:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3245: 未能解析此引用。未能找到程序集“Windows”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。 [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
ProcessResult.StdOut:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(17,15): error CS0234: 命名空间“Windows”中不存在类型或命名空间名“Management”(是否缺少程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
ProcessResult.StdOut:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,24): error CS0246: 未能找到类型或命名空间名“IAsyncOperationWithProgress<,>”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
ProcessResult.StdOut:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,52): error CS0246: 未能找到类型或命名空间名“DeploymentResult”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
ProcessResult.StdOut:   D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,70): error CS0246: 未能找到类型或命名空间名“DeploymentProgress”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
CommandUtils.Run: Took 4.3317153s to run MSBuild.exe, ExitCode=1
Log.WriteException: ==============================================================================
Log.WriteException: ERROR: Failed to build "D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved\UATTempProj.proj":
Log.WriteException:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3245: 未能解析此引用。未能找到程序集“Windows”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。 [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException:        D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(17,15): error CS0234: 命名空间“Windows”中不存在类型或命名空间名“Management”(是否缺少程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException:        D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,24): error CS0246: 未能找到类型或命名空间名“IAsyncOperationWithProgress<,>”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException:        D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,52): error CS0246: 未能找到类型或命名空间名“DeploymentResult”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException:        D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,70): error CS0246: 未能找到类型或命名空间名“DeploymentProgress”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException:        
Log.WriteException:        (see D:\UGit\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)
Log.WriteException: 
Log.WriteException: AutomationException: Failed to build "D:/UGit/UnrealEngine/Engine/Programs/AutomationTool/Saved\UATTempProj.proj":
Log.WriteException: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): warning MSB3245: 未能解析此引用。未能找到程序集“Windows”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。 [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException: D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(17,15): error CS0234: 命名空间“Windows”中不存在类型或命名空间名“Management”(是否缺少程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException: D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,24): error CS0246: 未能找到类型或命名空间名“IAsyncOperationWithProgress<,>”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException: D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,52): error CS0246: 未能找到类型或命名空间名“DeploymentResult”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException: D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,70): error CS0246: 未能找到类型或命名空间名“DeploymentProgress”(是否缺少 using 指令或程序集引用?) [D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
Log.WriteException: 
Log.WriteException:    在 AutomationTool.ScriptCompiler.CompileAutomationProjects(List`1 Projects, Dictionary`2 MsBuildProperties) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\ScriptCompiler.cs:行号 363
Log.WriteException:    在 AutomationTool.ScriptCompiler.FindAndCompileAllScripts(String ScriptsForProjectFileName, List`1 AdditionalScriptsFolders) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\ScriptCompiler.cs:行号 79
Log.WriteException:    在 AutomationTool.Automation.Process(String[] Arguments, StartupTraceListener StartupListener) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:行号 478
Log.WriteException:    在 AutomationTool.Program.MainProc(String[] Arguments, StartupTraceListener StartupListener) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:行号 175
Log.WriteException:    在 AutomationTool.Program.<>c__DisplayClass1_0.<Main>b__2() 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:行号 87
Log.WriteException:    在 AutomationTool.InternalUtils.RunSingleInstance(Func`1 Main) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:行号 737
Log.WriteException:    在 AutomationTool.Program.Main(String[] Arguments) 位置 D:\UGit\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:行号 87
Log.WriteException: ==============================================================================
Program.Main: AutomationTool exiting with ExitCode=1 (Error_Unknown)

**Comment by DecoyRS** [comment]
Hi @cloudxunuo 
At this moment, there's a known issue with non-utf8 symbols in User folder that prevents Rider from building RiderLink auto-matically. Actually, it's a problem from cl-filter.exe that is provided by Epic Games, but we're in the process of creating a workaround :)
Meanwhile, you can:
* Find RiderLink.zip under Rider installation folder;
* Unzip it into {Game}/Plugins/Developer/RiderLink
* Build youe game

**Comment by DecoyRS** [comment]
Duplicate for https://github.com/JetBrains/UnrealLink/issues/52
