### ISSUE TITLE
How to install plugin to Engine after installing it to Game?

### ISSUE THREAD

**Issue by slonopotamus** [JetBrains/UnrealLink#118]
I'm using:

Rider 2021.1.3
UnreallLink: 2021.1.12
Unreal Engine: 5.0EA2.

I once clicked "install plugin to Game". And now I can't undo that decision. Even if I fully remove plugin from the game and restart Rider, it will install UnrealLink back to game without asking me anything.

**Comment by DecoyRS** [comment]
Hi @slonopotamus 
About auto installing plugin into the game - check if you have option set to "auto update" plugin in `File | Settings | Languages & Frameworks | Unreal Engine`. 
About changing installation place, you have multiple options:
* As described in the [documentation for the plugin](https://github.com/JetBrains/UnrealLink#installation) In `File | Settings | Languages & Frameworks | Unreal Engine`, there are options to move the plugin to Game or Engine;
* You can press "Ctrl + Shift + A" to open "Run Actions" popup in Rider and type "Install RiderLink" and there will be 2 options, to install in Game, or in Editor;
* You can manually move plugin from the Game to the Engine, from {GameFolder}/Plugins/Developer/Riderlink into {EngineFolder}/Engine/Plugins/Developer/RiderLink

**Comment by slonopotamus** [comment]
Thanks, I somehow missed info about `File | Settings | Languages & Frameworks | Unreal Engine` menu.
