### ISSUE TITLE
RiderLink plugin install fails on fresh Rider installation

### ISSUE THREAD

**Issue by Gianluca-Cientanni** [JetBrains/UnrealLink#119]
Rider for Unreal Engine v2021.1.3
Unreal Engine v4.26.2-15973114+++UE4+Release-4.26
macOS BigSur v11.4 (20F71)
Xcode v12.5.1 (12E507)

**Error from RiderLink Install Progress tab within Rider Editor: **

--------------------------------------

`Running AutomationTool...

Running bundled mono, version: Mono JIT compiler version 5.16.0.220 (2018-06/bb3ae37d71a Fri Nov 16 17:12:11 EST 2018)
Start UAT: mono AutomationTool.exe BuildPlugin -Unversioned -Plugin=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Jyhabyl/RiderLink.uplugin -Package=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos
Parsing command line: BuildPlugin -Unversioned -Plugin=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Jyhabyl/RiderLink.uplugin -Package=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos
Using xbuild. Install Mono 5.0 or greater for faster builds!
Copying 368 file(s) using max 64 thread(s)
Reading plugin from /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/RiderLink.uplugin...
Building plugin for host platforms: Mac
Running: mono "/Users/Shared/Epic Games/UE_4.26/Engine/Binaries/DotNET/UnrealBuildTool.exe" UE4Editor Mac Development -Project=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/HostProject.uproject -plugin=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/RiderLink.uplugin -iwyu -noubtmakefiles -manifest=/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Saved/Manifest-UE4Editor-Mac-Development.xml -nohotreload -log="/Users/gianluca/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UE4Editor-Mac-Development.txt"
  Parsing headers for UE4Editor
    Running UnrealHeaderTool "/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/HostProject.uproject" "/var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Intermediate/Build/Mac/x86_64/UE4Editor/Development/UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/Users/gianluca/Library/Logs/Unreal Engine/LocalBuildLogs/UHT-UE4Editor-Mac-Development.txt" -installed
  Reflection code generated for UE4Editor in 7.6353597 seconds
  Writing manifest to /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Saved/Manifest-UE4Editor-Mac-Development.xml
  Building UE4Editor...
  Performing 67 actions (8 in parallel)
  [5/67] Compile SignalCookie.cpp
  [3/67] Compile hashing.cpp
  [8/67] Compile RdExtBase.cpp
  [7/67] Compile MessageBroker.cpp
  [6/67] Compile SynchronousScheduler.cpp
  [1/67] Compile SharedPCH.Core.RTTI.ShadowErrors.h
  [2/67] Compile async.cpp
  [4/67] Compile fmt.cpp
  [9/67] Compile ActiveSocket.cpp
  [10/67] Compile IProtocol.cpp
  [11/67] Compile Protocol.cpp
  [12/67] Compile ByteBufferAsyncProcessor.cpp
  [13/67] Compile ExtWire.cpp
  [14/67] Compile Buffer.cpp
  [15/67] Compile SingleThreadScheduler.cpp
  In file included from /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/Source/RD/src/rd_framework_cpp/src/main/protocol/Buffer.cpp:3:
  /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/Source/RD/src/rd_framework_cpp/src/main/protocol/Buffer.h:149:24: error: call to 'size' is ambiguous
                  const int32_t& len = size(container);
                                       ^~~~
  /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/Source/RD/src/rd_framework_cpp/src/main/protocol/Buffer.cpp:162:9: note: in instantiation of function template specialization 'rd::Buffer::write_array<std::vector, unsigned short, std::__1::allocator<unsigned short>, void>' requested here
          buffer.write_array<std::vector, uint16_t>(v);
                 ^
  /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/Source/RD/src/rd_framework_cpp/src/main/protocol/Buffer.cpp:195:2: note: in instantiation of function template specialization 'rd::write_wstring_spec<4>' requested here
          write_wstring_spec<sizeof(wchar_t)>(*this, value);
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:1962:16: note: candidate function [with _Cont = std::__1::vector<unsigned short>]
  constexpr auto size(const _Cont& __c)
                 ^
  /var/folders/43/f7q814gj0tjdx3gr7rfvwpww0000gn/T/UnrealLink/Qugunos/HostProject/Plugins/RiderLink/Source/RD/src/rd_core_cpp/src/main/std/list.h:10:9: note: candidate function [with T = std::__1::vector<unsigned short>] has been explicitly deleted
  int32_t size(T const& value) = delete;
          ^
  1 error generated.
  [16/67] Compile PkgInputStream.cpp
  [17/67] Compile stdout_sinks.cpp
  [18/67] Compile ISerializable.cpp
  [19/67] Compile RdReactiveBase.cpp
  [20/67] Compile thirdparty.cpp
  [21/67] Compile DefaultAbstractDeclaration.cpp
  [22/67] Compile SimpleSocket.cpp
  [23/67] Compile DateTime.cpp
  [24/67] Compile countdownlatch.cpp
  [25/67] Compile RdId.cpp
  [26/67] Compile Polymorphic.cpp
  [27/67] Compile PumpScheduler.cpp
  [28/67] Compile RD.cpp
  [29/67] Compile RdBindableBase.cpp
  [30/67] Compile RdAny.cpp
  [31/67] Compile SequentialLifetimes.cpp
  [32/67] Compile spdlog.cpp
  [33/67] Compile color_sinks.cpp
  [34/67] Compile Lifetime.cpp
  [35/67] Compile SerializationCtx.cpp
  [36/67] Compile InternRoot.cpp
  [37/67] Compile RName.cpp
  [38/67] Compile SingleThreadSchedulerBase.cpp
  [39/67] Compile WireUtil.cpp
  [40/67] Compile SocketWire.cpp
  [41/67] Compile IScheduler.cpp
  [42/67] Compile cfg.cpp
  [43/67] Compile ISerializersOwner.cpp
  [44/67] Compile WireBase.cpp
  [45/67] Compile IRdWireable.cpp
  [46/67] Compile Serializers.cpp
  [47/67] Compile thread_util.cpp
  [48/67] Compile LifetimeDefinition.cpp
  [49/67] Compile LifetimeImpl.cpp
  [50/67] Compile IUnknownInstance.cpp
  [51/67] Compile PassiveSocket.cpp
  [52/67] Compile RdTextBuffer.cpp
  [53/67] Compile Identities.cpp
  [54/67] Compile file_sinks.cpp
  [55/67] Compile InternScheduler.cpp
  [56/67] Compile SimpleScheduler.cpp
  [57/67] Compile SharedPCH.UnrealEd.RTTI.ShadowErrors.h
  [58/67] Compile Module.RiderLink.cpp
  [59/67] Compile Module.RiderLoggingExtension.cpp
  [60/67] Compile Module.RiderBlueprintExtension.cpp
  [61/67] Compile RiderGameControlExtension.cpp
Took 116.438629s to run mono, ExitCode=6
UnrealBuildTool failed. See log for more details. (/Users/gianluca/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UE4Editor-Mac-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
RunUAT ERROR: AutomationTool was unable to run successfully.
Failed to build RiderLink plugin
Failed to build RiderLink plugin
`

--------------------------------------

Despite this I can get some successful builds from Unreal, but it seems when I use certain libraries it breaks. The following screenshots show the errors in the Engine files I get when using collision logic.
<img width="963" alt="Screenshot 2021-07-06 at 14 30 37" src="https://user-images.githubusercontent.com/40888595/124611509-6c02fe80-de69-11eb-96c6-557191474caf.png">
<img width="376" alt="Screenshot 2021-07-06 at 14 27 54" src="https://user-images.githubusercontent.com/40888595/124611579-7c1ade00-de69-11eb-9964-4c1f8e9c5504.png">

**Comment by Gianluca-Cientanni** [comment]
Log from LocalBuildLogs/UBT-UE4Editor-Mac-Development.txt:

`Timeline.Print:  10.727          [ 9.882](+1.936) UEBuildTarget.PreBuildSetup()
Timeline.Print: [12.666](+15.273) UEBuildTarget.Build()
Timeline.Print:  12.666          [ 0.000](+0.140) <unknown>
Timeline.Print:  12.806          [ 0.140](+6.644) ExternalExecution.SetupUObjectModules()
Timeline.Print:  19.451          [ 6.785](+0.070) <unknown>
Timeline.Print:  19.521          [ 6.855](+7.634) Executing UnrealHeaderTool
Timeline.Print:  27.163          [14.496](+0.003) ExternalExecution.ResetCachedHeaderInfo()
Timeline.Print:  27.166          [14.500](+0.000) ExternalExecution.UpdateDirectoryTimestamps()
Timeline.Print:  27.183          [14.517](+0.281) UEBuildBinary.Build()
Timeline.Print:  27.464          [14.798](+0.474) <unknown>
Timeline.Print: [27.944](+0.001) ActionGraph.CheckPathLengths
Timeline.Print: [27.954](+0.000) Reading action history
Timeline.Print: [27.954](+0.002) Reading dependency cache
Timeline.Print: [27.958](+0.041) Prefetching include dependencies
Timeline.Print: [27.999](+0.057) Cache outdated actions
Timeline.Print: [28.057](+0.035) <unknown>
Timeline.Print: [28.092](+88.097) ActionGraph.ExecuteActions()
Timeline.Print: [116.189](+0.051) <unknown>
Timeline.Print: [116.240](+0.000) FileMetadataPrefetch.Stop()
Timeline.Print: [116.241]`

**Comment by Gianluca-Cientanni** [comment]
[Log.txt](https://github.com/JetBrains/UnrealLink/files/6770604/Log.txt)
[UBT-UE4Editor-Mac-Development.txt](https://github.com/JetBrains/UnrealLink/files/6770605/UBT-UE4Editor-Mac-Development.txt)

**Comment by DecoyRS** [comment]
Hi @Gianluca-Cientanni 
Please, update UnrealLink plugin in Rider with `Settings > Pluigns > Installed > UnrealLink > Update`

**Comment by Gianluca-Cientanni** [comment]
Thank you Alexander - it now installs RiderLink successfully. Sadly the other errors persist but at least it's not related to RiderLink.
