### ISSUE TITLE
"Package Project" disconnects Rider resulting in the Unreal Engine having to be restarted.

### ISSUE THREAD

**Issue by blakejrobinson** [JetBrains/UnrealLink#12]
If you use the File->Package Project feature of Unreal, the IPC connection to the engine is lost at the very end with a final log entry:

"Fri May 01 05:10:51 BST 2020 Log          LogModuleManager     Shutting down and abandoning module RiderLink (346)"

The engine must then be restarted to integrate with Rider again.

I'm using standard Unreal 4.24 (no plugins other than Rider integration).
RiderLink 2020.1.7

**Comment by DecoyRS** [comment]
All modules in RiderLink will have "Type : EditorNoCommandlet". It should prevent RiderLink from starting during packaging thous it won't be dropping old connection Rider <> Unreal Editor.

Available in Rider for Unreal Engine 2020.2.1 (To be released this week)
https://github.com/JetBrains/UnrealLink/releases/tag/v2020.2.36

If this issues will remain after the update, feel free to re-open this issue!
Cheers!
