### ISSUE TITLE
Having rider link plugin installed to the project breaks Android Cooking

### ISSUE THREAD

**Issue by lab-one** [JetBrains/UnrealLink#13]
Had my own project, but I guess could be reproduced with a default one.

1. Install Android Codeworks
2. Try to package project for Android
Observer crash related to RiderLink plugin in BuildUAT

**Comment by lab-one** [comment]
![image](https://user-images.githubusercontent.com/8478846/80943615-ea888a00-8de7-11ea-8d75-f1b4c2d8c430.png)

Sorry for a bad image, this is the only one I have. I removed plugin now and don't have time to repro it.

**Comment by DecoyRS** [comment]
This bug was fixed in Rider for UE 2020.1.2. Ease, update to latest version
