### ISSUE TITLE
Can't install newest rider link when using UE 4.23.

### ISSUE THREAD

**Issue by RandomInEqualities** [JetBrains/UnrealLink#135]
Hi. The RightChopInline function is not present in UE 4.23 so it fails to compile the plugin. It also looks like there is some issue with 'LoggingScheduler':

`
RiderLoggingExtension.hpp(26): error C2143: syntax error: missing ';' before '<'

RiderLoggingExtension.hpp(26): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

RiderLoggingExtension.hpp(26): error C2238: unexpected token(s) preceding ';'

RiderLoggingExtension.cpp(77): error C2039: 'RightChopInline': is not a member of 'FString'

WindowsCriticalSection.h(9): note: see declaration of 'FString'

RiderLoggingExtension.cpp(105): error C2065: 'LoggingScheduler': undeclared identifier

RiderLoggingExtension.cpp(121): error C2065: 'LoggingScheduler': undeclared identifier
`

(this is when using Visual Studio 2019)

**Comment by ddimkovikj** [comment]
@DecoyRS [this](https://github.com/JetBrains/UnrealLink/commit/d70c0d68e6044a04f31486956fd6a7ff1f0b0807) appears to be the commit that broke backwards compatibility with UE 4.23 and 4.24.
At least regarding to 'RightChopInline'.

**Comment by ddimkovikj** [comment]
Found a way around this bug and was able to successfully connect Rider with UE 4.24.
The workaround is to not to use the latest version of Rider for Unreal Engine, but the one before it - [2021.2](https://download-cdn.jetbrains.com/rider/cppDemo/JetBrains.Rider.For.Unreal.Engine-2021.2.Checked.exe).
This version does not have the abovementioned commit that broke the backwards compatibility with UE 4.24, will build, install the RiderLink to the UE and successfully connect to it.
