### ISSUE TITLE
Cannot build RiderLink in UE 4.19

### ISSUE THREAD

**Issue by vocasle** [JetBrains/UnrealLink#136]
> 11:41	Unreal Engine 4.23.0+ is required
			UnrealLink supports Unreal Engine versions starting with 4.23.0
			WARNING: Advanced users only
			You can manually download the latest version of plugin and build It for your version of Unreal Editor
			Download latest Unreal Editor plugin
			
Hello, as per warning suggestion I have tried to build UnrealLink from source.

I have successfully executed following commands:
```gradlew buildResharperHost```
```gradlew symlinkPluginToUnrealProject```.

After that I have regenerated project files via `GenerateProjectFiles.bat` and tried to build the game, but I have got an error from UBT:
```
  The first include statement in source file 'R:\<ProjectName>\<ProjectName>\Plugins\Developer\RiderLink\Source\RD\src\rd_framework_cpp\src\main\protocol\Buffer.cpp' is trying to include the file 'utility' as the precompiled header, but that file could not be located in any of the module's include search paths.
  ```
  
Could you please provide any suggestions on how to build RiderLink with UE 4.19?

**Comment by vocasle** [comment]
@DecoyRS may be you could suggest something? Or the only option is to upgrade Engine to 4.23?

**Comment by DecoyRS** [comment]
So the official stance would be "yes, you need to update to UE 4.23", but as a workaround, you can try to  add an empty file and set it as your PCH in RD.Build.cs

**Comment by kiferdon** [comment]
@vocasle Did you manage to build RiderLink eventually?
I added empty PCH file, but have another error:
  RiderGameControlExtension.cpp(20): [C1083] Cannot open include file: 'UnrealEd/Public/Editor.h': No such file or directory

**Comment by vocasle** [comment]
@kiferdon No, I have tried what DecoyRS suggested, but some new errors arose and I have stopped using Resharper after that)
