### ISSUE TITLE
Load failed: The project targets Unreal Engine version 4.24.3 error

### ISSUE THREAD

**Issue by ddimkovikj** [JetBrains/UnrealLink#138]
Latest versions seem to be incompatible with UE 4.24. I'm getting the following exception when trying to load an UE4 solution with RUE 2021.2:
load failed: The project targets Unreal Engine version 4.24.3
The message after that was something like: Minimum supported project version is 4.25.3 for this platform.

Where can I find older versions of RUE that support UE 4.24?

@DecoyRS maybe you can shed some light on this.

**Comment by hellg1** [comment]
They're located under %localappdata%\JetBrains\Rider2021.2\log, here we need something like backend.log and backend-err.log

**Comment by hellg1** [comment]
Wait, 

> I reinstalled 2021.2(not 2021.2.1) and it worked now. Not a clue what went wrong... I'll close this issue.

Wait, but how... Are you opening project via .sln now?
