### ISSUE TITLE
I can't set unreal engine to use rider on default

### ISSUE THREAD

**Issue by stunzeedjr** [JetBrains/UnrealLink#14]
if i go to source i can't see rider even though they are all on the same drive so i have to go to rider and hit open project and find the files

**Comment by stunzeedjr** [comment]
![Capture](https://user-images.githubusercontent.com/63565150/80994943-15340c00-8e03-11ea-8d56-a632cb1ed7de.PNG)

**Comment by DecoyRS** [comment]
@stunzeedjr UnrealLink doesn't provide this functionality. You need:
https://www.unrealengine.com/marketplace/en-US/product/rider-source-code-access

**Comment by stunzeedjr** [comment]
Ok thanks I got it working now
