### ISSUE TITLE
IDE failed to install UnrealLink plugin

### ISSUE THREAD

**Issue by gleplang-eidos** [JetBrains/UnrealLink#141]
Hello!

I have an issue while trying to pass from UnrealLink 2021.2.1.3 to 2021.2.1.4
When Rider restart, I have this popup:
![image](https://user-images.githubusercontent.com/60392730/139462811-733dfdd7-bdcf-47ef-a4fa-22ef72176d39.png)

If I click OK, it start normally with the older version, but what should I do to fix this?

Thanks!

**Comment by hellg1** [comment]
Hey there, I would recommend to restart Rider/delete this dll manually and try to update again. Honest fix of such problems will be available in 2021.3, sorry for inconvenience.

**Comment by gleplang-eidos** [comment]
Hi Hellg1,

Thank you very much that was the solution :)
