### ISSUE TITLE
Rider source code isn't compatible with UE 4.25.0

### ISSUE THREAD

**Issue by stunzeedjr** [JetBrains/UnrealLink#15]
Just downloaded the 4.25 so can you guys update the plugin thanks.

**Comment by DecoyRS** [comment]
Hello @stunzeedjr |
If you are talking about "RiderSourceCodeAccess" plugin, then it should be bundled with Unreal Engine, starting with version 4.25

**Comment by stunzeedjr** [comment]
oh ok

**Comment by stunzeedjr** [comment]
@DecoyRS 
can you guys add an option so when the autocomplete only shows up one option it actually autocompletes

**Comment by DecoyRS** [comment]
> option so when the autocomplete only shows up one option it actually autocompletes

![image](https://user-images.githubusercontent.com/1694911/81150853-12fbba00-8f89-11ea-8774-e9e05e3abfaf.png)

>jump from a string to the end of the parenthesis

Can you elaborate on this? Ideally, in Rider's task tracker:
https://youtrack.jetbrains.com/issues/RIDER 

>auto format when i click ; never works

https://youtrack.jetbrains.com/issue/RIDER-44054

For further questions regarding Rider functionality, I would kindly suggest to reference the documentation:
https://www.jetbrains.com/help/rider/Introduction.html
As for requests, bug reporting and troubleshooting, use Help menu that will navigate you to a corresponding page:
![image](https://user-images.githubusercontent.com/1694911/81150620-daf47700-8f88-11ea-8af5-631cef1f7e2e.png)
