### ISSUE TITLE
Failed to build RiderLink plugin

### ISSUE THREAD

**Issue by 2453852330** [JetBrains/UnrealLink#150]
Running AutomationTool...
Parsing command line: BuildPlugin -Unversioned -Plugin=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Dytuvyj\RiderLink.uplugin -Package=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix
Copying 371 file(s) using max 64 thread(s)
Reading plugin from C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\Plugins\RiderLink\RiderLink.uplugin...
Building plugin for host platforms: Win64
Running: D:\Epic\Install\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -Project=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\HostProject.uproject -plugin=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\Plugins\RiderLink\RiderLink.uplugin -iwyu -noubtmakefiles -manifest=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml -nohotreload -log="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Install+UE_4.26\UBT-UE4Editor-Win64-Development.txt"
  Parsing headers for UE4Editor
    Running UnrealHeaderTool "C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\HostProject.uproject" "C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Lunudix\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Install+UE_4.26\UHT-UE4Editor-Win64-Development.txt" -installed
  D:/Epic/Install/UE_4.26/Engine/Plugins/Marketplace/AudioAnalyzer/Source/AudioAnalyzer/Classes/AudioAnalyzerManager.h(309) : LogUObjectHash: Error: Ambiguous path search, could be Enum /Script/RuntimeAudioImporter.EAudioFormat or Enum /Script/ParallelcubeAudioAnalyzer.EAudioFormat
  D:/Epic/Install/UE_4.26/Engine/Plugins/Marketplace/AudioAnalyzer/Source/AudioAnalyzer/Classes/AudioAnalyzerManager.h(309) : Error: C++ Default parameter not parsed: AudioFormat "EAudioFormat::Signed_Int"
Took 5.4529603s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Install+UE_4.26\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

**Comment by 2453852330** [comment]
AndroidPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.AndroidPlatformSDK has no valid SDK
IOSPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.IOSPlatformSDK has no valid SDK
LinuxPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.LinuxPlatformSDK has no valid SDK
WindowsPlatformFactory.RegisterBuildPlatforms: UnrealBuildTool.WindowsPlatformSDK using manually installed SDK
BuildMode.Execute: Command line: "D:\Epic\Install\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe" UE4Editor Win64 Development -Project=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\HostProject.uproject -plugin=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\Plugins\RiderLink\RiderLink.uplugin -iwyu -noubtmakefiles -manifest=C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml -nohotreload -log="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Install+UE_4.26\UBT-UE4Editor-Win64-Development.txt"
DynamicCompilation.RequiresCompilation: Compiling C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\Intermediate\Build\BuildRules\HostProjectModuleRules.dll: Assembly does not exist
WindowsPlatform.FindVisualStudioInstallations: Found Visual Studio installation: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community (Product=Microsoft.VisualStudio.Product.Community, Version=16.11.31624.102)
WindowsPlatform.FindVisualStudioToolChains: Found Visual Studio toolchain: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133 (Version=14.29.30133)
WindowsPlatform.EnumerateSdkRootDirs: Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (1)
WindowsPlatform.EnumerateSdkRootDirs: Found Windows 10 SDK root at C:\Program Files (x86)\Windows Kits\10 (2)
WindowsPlatform.UpdateCachedWindowsSdks: Found Windows 10 SDK version 10.0.17763.0 at C:\Program Files (x86)\Windows Kits\10
WindowsPlatform.UpdateCachedWindowsSdks: Found Universal CRT version 10.0.17763.0 at C:\Program Files (x86)\Windows Kits\10
UEBuildTarget.AddPlugin: Enabling plugin 'RiderLink' (referenced via command line)
UEBuildTarget.AddPlugin: Enabling plugin 'Paper2D' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AISupport' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'EnvironmentQueryEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'LightPropagationVolume' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CameraShakePreviewer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AnimationSharing' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SignificanceManager' (referenced via default plugins -> AnimationSharing.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'CLionSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CodeLiteSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GitSourceControl' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'KDevelopSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'NullSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PerforceSourceControl' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PlasticSourceControl' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PluginUtils' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PropertyAccessNode' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PropertyAccessEditor' (referenced via default plugins -> PropertyAccessNode.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'RiderSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SubversionSourceControl' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'UObjectPlugin' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'VisualStudioCodeSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'VisualStudioSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'XCodeSourceCodeAccess' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AssetManagerEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ContentBrowserAssetDataSource' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ContentBrowserClassDataSource' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CryptoKeys' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CurveEditorTools' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'DataValidation' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'FacialAnimation' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GameplayTagsEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GeometryMode' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MacGraphicsSwitching' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MaterialAnalyzer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MobileLauncherProfileWizard' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PluginBrowser' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SpeedTreeImporter' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'DatasmithContent' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'VariantManagerContent' (referenced via default plugins -> DatasmithContent.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'AlembicImporter' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GeometryCache' (referenced via default plugins -> AlembicImporter.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'AutomationUtils' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ScreenshotTools' (referenced via default plugins -> AutomationUtils.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'BackChannel' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ChaosClothEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ChaosCloth' (referenced via default plugins -> ChaosClothEditor.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'ChaosEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PlanarCut' (referenced via default plugins -> ChaosEditor.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'GeometryProcessing' (referenced via default plugins -> ChaosEditor.uplugin -> PlanarCut.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'EditableMesh' (referenced via default plugins -> ChaosEditor.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'GeometryCollectionPlugin' (referenced via default plugins -> ChaosEditor.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'ProceduralMeshComponent' (referenced via default plugins -> ChaosEditor.uplugin -> GeometryCollectionPlugin.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'ChaosSolverPlugin' (referenced via default plugins -> ChaosEditor.uplugin -> GeometryCollectionPlugin.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'ChaosNiagara' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'Niagara' (referenced via default plugins -> ChaosNiagara.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'CharacterAI' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MotoSynth' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PlatformCrypto' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ProxyLODPlugin' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SkeletalReduction' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'LuminPlatformFeatures' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MLSDK' (referenced via default plugins -> LuminPlatformFeatures.uplugin)
LuminSDKVersionHelper.HasAnySDK: *** Unable to determine MLSDK location ***
UEBuildTarget.AddPlugin: Enabling plugin 'MagicLeapMedia' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MagicLeap' (referenced via default plugins -> MagicLeapMedia.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'MagicLeapPassableWorld' (referenced via default plugins -> MagicLeapMedia.uplugin -> MagicLeap.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'MagicLeapLightEstimation' (referenced via default plugins -> MagicLeapMedia.uplugin -> MagicLeap.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'AndroidMedia' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AvfMedia' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ImgMedia' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MediaCompositing' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MediaPlayerEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'WmfMedia' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MeshPainting' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'TcpMessaging' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'UdpMessaging' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ActorSequence' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'LevelSequenceEditor' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MatineeToLevelSequence' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'TemplateSequence' (referenced via default plugins -> MatineeToLevelSequence.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemGooglePlay' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystem' (referenced via default plugins -> OnlineSubsystemGooglePlay.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'AndroidPermission' (referenced via default plugins -> OnlineSubsystemGooglePlay.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemIOS' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemNull' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'OnlineSubsystemUtils' (referenced via default plugins -> OnlineSubsystemNull.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'LauncherChunkInstaller' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ActorLayerUtilities' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AndroidDeviceProfileSelector' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AndroidMoviePlayer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AppleImageUtils' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AppleMoviePlayer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ArchVisCharacter' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AssetTags' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AudioCapture' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CableComponent' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ChunkDownloader' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'CustomMeshComponent' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'ExampleDeviceProfileSelector' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GoogleCloudMessaging' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'GooglePAD' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'IOSDeviceProfileSelector' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'LinuxDeviceProfileSelector' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'LocationServicesBPLibrary' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'MobilePatchingUtils' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'OculusVR' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PhysXVehicles' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'PostSplashScreen' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'RuntimePhysXCooking' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SoundFields' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'SteamVR' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'Synthesis' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'AudioSynesthesia' (referenced via default plugins -> Synthesis.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'WebMMoviePlayer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'WebMMedia' (referenced via default plugins -> WebMMoviePlayer.uplugin)
UEBuildTarget.AddPlugin: Enabling plugin 'WindowsMoviePlayer' (referenced via default plugins)
UEBuildTarget.AddPlugin: Enabling plugin 'XGEController' (referenced via default plugins)
LuminSDKVersionHelper.HasAnySDK: *** Unable to determine MLSDK location ***
VCToolChain..ctor: Compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
VCToolChain..ctor: Linker: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe
VCToolChain..ctor: Library Manager: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\lib.exe
VCToolChain..ctor: Resource Compiler: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe
ExternalExecution.ExecuteHeaderToolIfNecessary: Parsing headers for UE4Editor
ExternalExecution.ExecuteHeaderToolIfNecessary:   Running UnrealHeaderTool "C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\HostProject.uproject" "C:\Users\Administrator\AppData\Local\Temp\UnrealLink\Pyzelas\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+Install+UE_4.26\UHT-UE4Editor-Win64-Development.txt" -installed
ExternalExecution.PrintProcessOutputAsync: D:/Epic/Install/UE_4.26/Engine/Plugins/Marketplace/AudioAnalyzer/Source/AudioAnalyzer/Classes/AudioAnalyzerManager.h(309) : LogUObjectHash: Error: Ambiguous path search, could be Enum /Script/RuntimeAudioImporter.EAudioFormat or Enum /Script/ParallelcubeAudioAnalyzer.EAudioFormat
ExternalExecution.PrintProcessOutputAsync: D:/Epic/Install/UE_4.26/Engine/Plugins/Marketplace/AudioAnalyzer/Source/AudioAnalyzer/Classes/AudioAnalyzerManager.h(309) : Error: C++ Default parameter not parsed: AudioFormat "EAudioFormat::Signed_Int"
UnrealBuildTool.Main: CompilationResultException: Error: OtherCompilationError
UnrealBuildTool.Main:    在 UnrealBuildTool.ExternalExecution.ExecuteHeaderToolIfNecessary(BuildConfiguration BuildConfiguration, FileReference ProjectFile, String TargetName, TargetType TargetType, Boolean bHasProjectScriptPlugin, List`1 UObjectModules, FileReference ModuleInfoFileName, Boolean bIsGatheringBuild, Boolean bIsAssemblingBuild, ISourceFileWorkingSet WorkingSet) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\System\ExternalExecution.cs:行号 1172
UnrealBuildTool.Main:    在 UnrealBuildTool.UEBuildTarget.Build(BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, Boolean bIsAssemblingBuild, List`1 SpecificFilesToCompile) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:行号 1729
UnrealBuildTool.Main:    在 UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:行号 615
UnrealBuildTool.Main:    在 UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, Boolean bSkipPreBuildTargets) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:行号 257
UnrealBuildTool.Main:    在 UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:行号 226
UnrealBuildTool.Main:    在 UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) 位置 D:\Build\++UE4\Sync\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:行号 550
Timeline.Print: Timeline:
Timeline.Print: 
Timeline.Print: [ 0.000]
Timeline.Print: [ 0.013](+0.002) FileMetadataPrefetch.QueueEngineDirectory()
Timeline.Print: [ 0.015](+0.087) XmlConfig.ReadConfigFiles()
Timeline.Print: [ 0.102](+0.000) SingleInstanceMutex.Acquire()
Timeline.Print: [ 0.102](+0.054) UEBuildPlatform.RegisterPlatforms()
Timeline.Print:   0.103          [ 0.000](+0.029) Initializing InstalledPlatformInfo
Timeline.Print:   0.133          [ 0.030](+0.000) Querying types
Timeline.Print:   0.134          [ 0.031](+0.001) MacPlatformFactory
Timeline.Print:   0.135          [ 0.032](+0.000) TVOSPlatformFactory
Timeline.Print:   0.135          [ 0.033](+0.015) AndroidPlatformFactory
Timeline.Print:   0.151          [ 0.048](+0.000) HoloLensPlatformFactory
Timeline.Print:   0.151          [ 0.048](+0.002) IOSPlatformFactory
Timeline.Print:   0.153          [ 0.050](+0.002) LinuxPlatformFactory
Timeline.Print:   0.156          [ 0.053](+0.000) LuminPlatformFactory
Timeline.Print:   0.156          [ 0.053](+0.000) WindowsPlatformFactory
Timeline.Print: [ 0.161](+0.009) TargetDescriptor.ParseCommandLine()
Timeline.Print: [ 0.175](+0.886) UEBuildTarget.Create()
Timeline.Print:   0.177          [ 0.002](+0.182) RulesCompiler.CreateTargetRulesAssembly()
Timeline.Print:   0.177            0.002          [ 0.000](+0.057) <unknown>
Timeline.Print:   0.235            0.059          [ 0.057](+0.023) Finding engine modules
Timeline.Print:   0.258            0.083          [ 0.081](+0.003) Finding plugin modules
Timeline.Print:   0.261            0.086          [ 0.084](+0.023) <unknown>
Timeline.Print:   0.285            0.110          [ 0.107](+0.003) Finding program modules
Timeline.Print:   0.289            0.114          [ 0.111](+0.002) Finding program targets
Timeline.Print:   0.294            0.118          [ 0.116](+0.060) Compiling rules assembly (HostProjectModuleRules.dll)
Timeline.Print:   0.359          [ 0.184](+0.052) RulesAssembly.CreateTargetRules()
Timeline.Print:   0.420          [ 0.245](+0.003) UEBuildTarget constructor
Timeline.Print:   0.423          [ 0.248](+0.637) UEBuildTarget.PreBuildSetup()
Timeline.Print: [ 1.063](+3.876) UEBuildTarget.Build()
Timeline.Print:   1.063          [ 0.000](+0.080) <unknown>
Timeline.Print:   1.144          [ 0.080](+0.553) ExternalExecution.SetupUObjectModules()
Timeline.Print:   1.698          [ 0.634](+0.027) <unknown>
Timeline.Print:   1.725          [ 0.661](+3.213) Executing UnrealHeaderTool
Timeline.Print: [ 4.939](+0.031) <unknown>
Timeline.Print: [ 4.971](+0.000) FileMetadataPrefetch.Stop()
Timeline.Print: [ 4.974]

**Comment by DecoyRS** [comment]
Hello!
You have problems with AudioAnalyzer plugin from marketplace. Removing/fixing it should solve the problem. Cheers!

**Comment by 2453852330** [comment]
thanks
