### ISSUE TITLE
Failed to build RiderLink v2021.3.0.271

### ISSUE THREAD

**Issue by carl-haven** [JetBrains/UnrealLink#154]
When trying to upgrade the RiderLink plugin from 2021.3.0.2 to 2021.3.0.271 we get the following error:

```
AppData\Local\Temp\UnrealLink\Boxomic\HostProject\Plugins\RiderLink\Source\RD\src\rd_framework_cpp\src\main\wire\SocketWire.cpp(119): error C2220: the following warning is treated as an error
    AppData\Local\Temp\UnrealLink\Boxomic\HostProject\Plugins\RiderLink\Source\RD\src\rd_framework_cpp\src\main\wire\SocketWire.cpp(119): warning C4267: 'argument': conversion from 'size_t' to 'const T', possible loss of data
```

Looking at the code `SocketWire.cpp line 119 is missing a static_cast<int32_t>`

**Comment by ArtemiyAAA** [comment]
Hello, @carl-haven 
Thanks for feedback! The issue fixed https://youtrack.jetbrains.com/issue/RIDER-73850. Please try latest commit https://github.com/JetBrains/UnrealLink/commit/e5233121e3ade37b152acd1a02f55eb1303ac4cf
