### ISSUE TITLE
Unreal Link plugin, being enabled, requires additional plugin com.jetbrains.rider-cpp

### ISSUE THREAD

**Issue by poploveok** [JetBrains/UnrealLink#156]
![nolink](https://user-images.githubusercontent.com/63087390/154103500-0168d0a7-aeda-4c96-ad8d-09548ad600f7.png)
how to finish the installation. thx.

**Comment by DecoyRS** [comment]
UnrealLink plugin can be installed only in "Rider" with C++ support. It's either "Rider for Unreal Engine" or "Rider" starting with 2022.1 build. Both of these versions have UnrealLink plugin already bundled, so in general you very rarely need to explicitly install this plugin.
