### ISSUE TITLE
Plugin error. Plugin 'UnrealLink' requires plugin 'com.jetbrains.rider-cpp' to be installed

### ISSUE THREAD

**Issue by poploveok** [JetBrains/UnrealLink#158]
Plugin error. Plugin 'UnrealLink' requires plugin 'com.jetbrains.rider-cpp' to be installed 
hlp pls
![nolink](https://user-images.githubusercontent.com/63087390/154546973-0b0b6714-8eab-4463-83d8-8b661741ea2c.png)
d

**Comment by DecoyRS** [comment]
As I've mentioned in the previous your post, you need to make sure you have either "Rider for Unreal Engine" or "Rider 2022.1 EAP" installed. Make sure that you have one of these versions installed and UnrealLink Wil work properly.

**Comment by Elie-Y** [comment]
I had the same issue, I was trying to get Rider 2022.1.2 to work with Unreal and wasn't able to create a C++ project, so I downgraded Rider but got the same error as you. So I reinstalled Rider 2022.1.2 and installed VS2019 build tools then installed the required libraries and tools such as MSVC, Windows SDK, .NET SDK and runtime... and it works fine.

**Comment by ArtemiyAAA** [comment]
@Elie-Y Yes, you need some requirements for working with C++/Unreal projects
**Software requirements**﻿
Unreal Engine 4.20+ (Unreal Engine 4.25.4+ to work with .uproject directly)
MSVC compiler (Visual Studio 2013, 2015, 2017, or 2019) for Unreal Engine projects, or Clang for other C++ projects.

**Comment by l-t-m-f** [comment]
This can be caused by sharing settings with Backup & Sync if you have CLion and Jetbrains and use sync between "All Jetbrains IDE products". It just happened to me.
