### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by ericwomer** [JetBrains/UnrealLink#16]
For those who want to test the newest features from github there are no build/configure instructions to get it all compiled.

**Comment by DecoyRS** [comment]
Hi @ericwomer !

This is intentional as stated in documentation:
> WARNING:
> RiderLink plugin for Unreal Editor is not intended to be installed manually. Rather it should be installed by Rider to ensure compatibility.

Compatibility aside, manually installed plugin will have higher priority over bundled plugin and will prevent normal flow of updates.

State of documentation may change in the future, but meanwhile, this is intended.
