### ISSUE TITLE
Extremely long log entry causes RiderLink to lose connection to Unreal Engine

### ISSUE THREAD

**Issue by andrewjli** [JetBrains/UnrealLink#17]
In order to easily debug network requests, the project I've been working on prints all responses to log. Unfortunately, as the game has grown and features have been added, some of these responses have become very big, with the largest one (where all the player's data is sent in one go) reaching almost 29,000 characters. When this happens, an exception seems to occur, and the Unreal Engine Log panel stops updating, and if debugging, this message begins to appear every couple of seconds in the debugging output:

```
UnrealEditorServer-XXXXXX: failed to send ping over the network, reason: Connection was forcibly closed by the remote host.
UnrealEditorServer-XXXXXX: failed to send ping over the network, reason: Connection was forcibly closed by the remote host.
```

Commenting out the `UE_LOG` statement responsible for the giant log does prevent this from occurring, so I'm fairly confident that's the reason. I'm not entirely sure if this is the corresponding exception, but my `backend-err.log` file is full of these so I think this is correct. It's in Japanese unfortunately, but it's the normal `Destination array is not long enough to copy all the items in the collection. Check array index and length.` exception.

```
ターゲット配列の長さが足りません。destIndex、長さ、および配列の最小値を確認してください。

--- EXCEPTION #1/2 [ArgumentException]
Message = ターゲット配列の長さが足りません。destIndex、長さ、および配列の最小値を確認してください。
ExceptionPath = Root.InnerException
ClassName = System.ArgumentException
HResult = E_INVALIDARG=COR_E_ARGUMENT=WIN32_ERROR_INVALID_PARAMETER=80070057
Source = mscorlib
StackTraceString = “
  場所 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
     場所 JetBrains.Rd.Impl.BufferWindow.Read(BufferWindow& helper, Receiver receiver, Int32 size)
     場所 JetBrains.Rd.Impl.SocketWire.Base.ReceiveFromPkgBuffer(Byte[] buffer, Int32 offset, Int32 size)
     場所 JetBrains.Rd.Impl.BufferWindow.Read(BufferWindow& helper, Receiver receiver, Int32 size)
     場所 JetBrains.Rd.Impl.SocketWire.Base.ReadMsg()
     場所 JetBrains.Rd.Impl.SocketWire.Base.ReceiverProc(Socket socket)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = ターゲット配列の長さが足りません。destIndex、長さ、および配列の最小値を確認してください。
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  場所 JetBrains.Rd.Impl.SocketWire.Base.ReceiverProc(Socket socket)
     場所 JetBrains.Rd.Impl.SocketWire.Base.<>c__DisplayClass19_0.<.ctor>b__1(Socket socket)
     場所 JetBrains.Collections.Viewable.Signal`1.Fire(T value)
     場所 JetBrains.Collections.Viewable.ViewableProperty`1.set_Value(T value)
     場所 JetBrains.Rd.Impl.SocketWire.Client.<>c__DisplayClass1_0.<.ctor>b__0()
     場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     場所 System.Threading.ThreadHelper.ThreadStart()
”
```

**Comment by DecoyRS** [comment]
Hello @andrewjli! What version of "Rider for Unreal Engine" and UnrealLink plugin do you have installed?

**Comment by andrewjli** [comment]
Whoops! After writing all the details, that completely slipped my mind! Apologies for that!

Version details for Rider for Unreal Engine:
```
Rider for Unreal Engine 2020.1.2
Build #RDCPPP-201.7189.55, built on April 26, 2020
Runtime version: 11.0.6+8-b765.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
.NET Framework 4.0.30319.42000
```

Unreal Link / Rider Link should be version 2020.1.7. It's the version that was installed automatically. Is it just old?

**Comment by DecoyRS** [comment]
No, 2020.1.7 is a correct version) It doesn't have an auto update right now and new versions should be acquired through updates of Rider.
I've fixed a situation where someone had a git plugin logging command lines with more than 600k symbols in it, but I was able to divide incoming log message by line separators '\n'.
In your case, do you have a single huge line? The way that Blueprint's links a processed right now is extremely ineffective and I'm working on fixing it, meanwhile you can workaround this issue with adding:
`tail = tail.Left(1000);`
in RiderLink.cpp at line 261. It will trancuate outgoing messages to 1000 symbols

**Comment by southrop** [comment]
Hi,

Yeah, it looks like the 29k char log is all a single line. It's basically a giant JSON string. Interestingly, Unreal Engine's Output Log window actually breaks it up into multiple lines (maybe that's a "feature" of the output log window).

Adding the truncate line to `RiderLink.cpp` works as intended, and it's good enough for me for now! If I need to view that full log, I can always check UE4's Output Log.

**Comment by andrewjli** [comment]
Hi,

Yeah, it looks like the 29k char log is all a single line. It's basically a giant JSON string. Interestingly, Unreal Engine's Output Log window actually breaks it up into multiple lines (maybe that's a "feature" of the output log window).

Adding the truncate line to RiderLink.cpp works as intended, and it's good enough for me for now! If I need to view that full log, I can always check UE4's Output Log.
