### ISSUE TITLE
Where is the Unreal Output Log window?

### ISSUE THREAD

**Issue by RandyCroucher** [JetBrains/UnrealLink#172]
I've installed Rider for Unreal Engine 2022.1 Build #RDCPPP-221.5080.76 on a new machine and can't figure out how to show the log messages coming from Unreal.  There used to be a panel for it.

Here's an image of it I found on the web...
![image](https://user-images.githubusercontent.com/11234457/163296803-b2708bd7-a006-4359-a9cc-f1c515f1ecd0.png)

How do I get it to show up now?

**Comment by DecoyRS** [comment]
Hello RandyCroucher,

The panel should show up as soon as you get connection with Unreal Editor.
Check these things:
* UnrealLink plugin is enabled in Rider
* RiderLink plugin is installed and enabled in Unreal Editor
* After starting Unreal Editor connection is established - bottom right corner of Rider should have an indication for it

**Comment by RandyCroucher** [comment]
Ah, I see.  The problem there is that I can't get it to compile.  :(  I'll try to get that figured out.  
Thank you!
