### ISSUE TITLE
Failed to build RiderLink plugin, then I try to manual copy it to the folder, but failed

### ISSUE THREAD

**Issue by Celestial-Plato** [JetBrains/UnrealLink#173]
when I try  to copy the RiderLink  to developer folder, after open editor something wrong  pop up -
![image](https://user-images.githubusercontent.com/80942582/163303066-3ef11358-6ae0-4170-9f3e-d06645bcf3e4.png)

**Comment by DecoyRS** [comment]
Since UE5, Epic Games have disabled/broken this option, unfortunately :( I'm trying to figure out other options, but no option so far to have RiderLink plugin in the pre-built version of UE5
