### ISSUE TITLE
Plugin not compiling/linking with c++17

### ISSUE THREAD

**Issue by Frigerius** [JetBrains/UnrealLink#19]
If compiling the editor with c++17, the plugin can't be linked with the provided libs. Is there a chance to get the source code for the used libs? (And fixing the c++17 deprecation warnings^^)

**Comment by DecoyRS** [comment]
Hi @Frigerius !
Chances are, you are talking about the "RD" module that is provided as pre-built dlls.
You can find more info here:
https://github.com/JetBrains/rd
in "rd-cpp" folder.
Mind you that C++ port (that is used in UE4 at the moment) was in experimental stage and is undergoing heavy rework, including support for different C++ standards

**Comment by Frigerius** [comment]
Ah, great, thanks for the info :)
