### ISSUE TITLE
Cant close Unreal log window

### ISSUE THREAD

**Issue by AJIADb9** [JetBrains/UnrealLink#2]
Cant close Unreal log window
![image](https://user-images.githubusercontent.com/8657156/79759475-659d6b00-8327-11ea-86ae-f1a7c4afe869.png)

**Comment by MyLovePoppet** [comment]
Hey, How‘s it going now?
I can't close the Unreal log window to, and when i started the Unreal Editor, The mouse cursor seems to be locked on this Unreal log window, so I can't start edit my code in Rider when the Unreal Editor is started.
![image](https://user-images.githubusercontent.com/40077724/84096691-217c3c00-aa35-11ea-9c46-247e027c6d6e.png)
![image](https://user-images.githubusercontent.com/40077724/84096721-32c54880-aa35-11ea-833a-05d499bfd224.png)

**Comment by DecoyRS** [comment]
Hi @MyLovePoppet! You've got pretty interesting case. Do you have any exceptions in Rider (red exclamation mark in bottom right corner)? Also, can you share contents of output window from Unreal Editor? As a workaround, you can remove RiderLoggingExtension from RiderLink plugin, it will disable functionality regarding log panel.

**Comment by MyLovePoppet** [comment]
Thanks! I removed the RiderLink plugin in UE4 Editor, that works for me, I can code in the Rider when the UE4 Editor is started.
