### ISSUE TITLE
Are there going to be any updates for the Rider Link? Unable to build Unreal Link plugin.

### ISSUE THREAD

**Issue by Pirog17000** [JetBrains/UnrealLink#200]
The last time RiderLink was updated Feb02
It's August.
Rider itself has been updated many many times.

It makes me use the older version of the main software because the plugin is not supported by later versions.

**Comment by DecoyRS** [comment]
Hello @Pirog17000
UnrealLink/RiderLink is distributed as a bundled plugin with Rider. Every new version of Rider takes the latest source code of UnrealLink, builds it and packs alongside.

**Comment by Pirog17000** [comment]
Build #RD-222.3345.88, built on July 20, 2022   seems to not have one bundled then? 
The latest available version, but Unreal Link refuses to build with it. My question grows out of this issue.

**Comment by Pirog17000** [comment]
![image](https://user-images.githubusercontent.com/3022852/182376379-d31dd262-5a87-40e9-a17b-017a139b260a.png)
it ends almost instantly with this error:   Failed to build RiderLink plugin

**Comment by Pirog17000** [comment]
Turns out the problem has been in the broken system 'cmd' tool, which wasn't able to run even itself.
Right after fixing this everything was compiled and updated smoothly.

And I fixed 'cmd' tool by removing AutoRun entry from registry:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor

Issue could be closed.
