### ISSUE TITLE
RiderLink shows references from UDataAssets but doesn't support opening them.

### ISSUE THREAD

**Issue by MT-Dev** [JetBrains/UnrealLink#234]
Rider will show references of UPROPERTIES from UDataAsset objects, but when selecting the reference from the Rider context menu, it won't open the UDataAsset in the Unreal Editor.

Replacing the call to 

`FKismetEditorUtilities::BringKismetToFocusAttentionOnObject(Blueprint);`

with

`GEditor->GetEditorSubsystem<UAssetEditorSubsystem>()->OpenEditorForAsset(Object);`

will allow it to work for both UBlueprint and UDataAsset objects.

**Comment by DecoyRS** [comment]
Thank you for the feedback! I think we've tried to use OpenEditorGorAsset in the first place, but it couldn't focus on the node that was referenced by the uproperty eg if you were to find a place where a field is being set up.  Not opening a UDataAsset is an issue for sure, but do you know if there's an API that would focus on a specific field of the UDataAsset?

**Comment by DecoyRS** [comment]
Whelp, I've fixed it and forgot to cherry pick the fix >< The next bugfix build of Rider (eg 2023.1.1) will have this fixed
