### ISSUE TITLE
UnrealLink expects Unreal in a different folder

### ISSUE THREAD

**Issue by Tobi0812** [JetBrains/UnrealLink#247]
UnrealLink expects Unreal 5.1 inside the folder Program Files (x86) but for me, Unreal is installed just in Program Files.
UnrealLink then throws me this error:

Failed to build RiderLink plugin for C:\Program Files (x86)\Epic Games\UE_5.1
Reason: RunUAT.bat is not available at expected destination: C:\Program Files (x86)\Epic Games\UE_5.1\Engine\Build\BatchFiles\RunUAT.bat
Failed to build RiderLink plugin

How can I tell UnrealLink that Unreal is in another directory?

**Comment by kaushal135** [comment]
Hi @Tobi0812 were you able to solve this?
