### ISSUE TITLE
Lost Run/Debug Configurations

### ISSUE THREAD

**Issue by Dgonzalez541** [JetBrains/UnrealLink#259]
Whatever run/debug configuration Rider was using by default disappeared. The list of configurations is empty. When trying to add a new one. No Unreal engine options appears, and looking around/testing, C++ project doesn't work.

**Comment by DecoyRS** [comment]
Hello @Dgonzalez541
This looks like bundled C++ plugin has crushed (or the whole language support backend). You need to report the crush to the Rider team and attach the logs. Help > Report a bug (check attach logs)
