### ISSUE TITLE
Recommended setup for designers

### ISSUE THREAD

**Issue by ThomasKasene** [JetBrains/UnrealLink#26]
I've noticed that the `*.uproject` file, which is checked into SCM, is updated with the RiderLink plugin when it's enabled, which means that the editor on designers' machines will try to enable it. This fails because the plugin isn't installed there.

I'm wondering what the recommended project configuration is for teams that have both designers and programmers? Naturally, the programmers will have Rider installed and working, but the designers might only have the Visual Studio Build Tools to compile their project.

Thanks in advance for any suggestions!

**Comment by DecoyRS** [comment]
Hi @ThomasKasene !
tl;dr, add `"EnabledByDefault": true,` to `RiderLink.uplugin` file.
We're using UnrealBuildTool to install plugin on users PC. During compilation, UnrealBuildTool copies RiderLink.uplugin file and deletes `"EnabledByDefault": true,` line for whatever reason.
I'll add a fix for the new version of plugin.

**Comment by redxdev** [comment]
I just started using Rider for UE4 and was having the same issue, my solution was to move RiderLink into the engine plugins directory (after building the plugin) and set `"EnabledByDefault": true` as mentioned above. Means that you don't need to install it into every project you work with and you keep it away from your project's source control since some users inevitably won't want it (designers, artists, programmers not using rider, etc).

**Comment by DecoyRS** [comment]
No more manually adding "EnabledByDefault", RiderLink.uplugin file will be patched on installation.
Available in Rider for Unreal Engine 2020.2.1 (To be released this week)
https://github.com/JetBrains/UnrealLink/releases/tag/v2020.2.34

**Comment by ThomasKasene** [comment]
Thank you for your response and solution! However, after the update I'm still having an issue where the plugin wants to update the `.uproject`-file. When I updated the plugin, I told it to install into the engine (as opposed to moving it into the game). When I launch my editor now, I get:

<img width="701" alt="post_update" src="https://user-images.githubusercontent.com/6691406/87848823-cff08800-c8e3-11ea-86cc-bce9113cb10e.png">

And if I press "Update" it adds this to my `.uproject`-file
```
"Plugins": [
	// ...
	{
		"Name": "RiderLink",
		"Enabled": true
	}
]
```

Of course, I can choose to not update the project file, but that will make the popup come back next time I launch the editor, and it's going to become a bit annoying and error-prone.

**Comment by DecoyRS** [comment]
@ThomasKasene some update - after building `RiderLink`, `UnrealBuildTool` was rewriting some values in `RiderLink.uplugin`. Specifically, it was adding `"Installed" : true` and this was triggering "Project file is out of date" popup.
Latest release of RiderLink (and next release of Rider for Unreal Engine) will have `"Installed" : false` patched and won't be showing this popup.
