### ISSUE TITLE
Rider Link don't compile on UE 5.2.1

### ISSUE THREAD

**Issue by seb-exiin** [JetBrains/UnrealLink#261]
Here are the errors i'm getting: (tried with the marketplace version 2022.2.0.182 and the tag [v2021.1.12])
  
  WiredRdTaskImpl.h(66): [C4250] 'rd::detail::WiredRdTaskImpl<T,S>': inherits 'rd::RdBindableBase::rd::RdBindableBase::get_protocol' via dominance
  RdBindableBase.h(25): [C4250] see declaration of 'rd::RdBindableBase::get_protocol'
  xmemory(2096): [C4250] see reference to class template instantiation 'rd::detail::WiredRdTaskImpl<T,S>' being compiled
  memory(2105): [C4250] see reference to class template instantiation 'std::_Wrap<_Ty>' being compiled
  memory(2764): [C4250] see reference to class template instantiation 'std::_Ref_count_obj2<_Ty>' being compiled
  WiredRdTask.h(21): [C4250] see reference to function template instantiation 'std::shared_ptr<rd::detail::WiredRdTaskImpl<T,S>> std::make_shared<rd::detail::WiredRdTaskImpl<T,S>,rd::Lifetime&,const rd::RdReactiveBase&,rd::RdId&,rd::IScheduler*&,rd::Property<rd::RdTaskResult<T,S>>*&>(rd::Lifetime &,const rd::RdReactiveBase &,rd::RdId &,rd::IScheduler *&,rd::Property<rd::RdTaskResult<T,S>> *&)' being compiled
  WiredRdTask.h(20): [C4250] while compiling class template member function 'rd::WiredRdTask<TRes,ResSer>::WiredRdTask(rd::Lifetime,const rd::RdReactiveBase &,rd::RdId,rd::IScheduler *)'
  RdCall.h(120): [C4250] see the first reference to 'rd::WiredRdTask<TRes,ResSer>::WiredRdTask' in 'rd::RdCall<int32_t,bool,rd::Polymorphic<T,void>,rd::Polymorphic<bool,void>>::start_internal'
  RdCall.h(74): [C4250] see the first reference to 'rd::RdCall<int32_t,bool,rd::Polymorphic<T,void>,rd::Polymorphic<bool,void>>::start_internal' in 'rd::RdCall<int32_t,bool,rd::Polymorphic<T,void>,rd::Polymorphic<bool,void>>::sync'
  RiderBlueprintExtension.cpp(24): [C4250] see the first reference to 'rd::RdCall<int32_t,bool,rd::Polymorphic<T,void>,rd::Polymorphic<bool,void>>::sync' in 'AllowSetForeGroundForEditor'
  RiderBlueprintExtension.cpp(24): [C4250] see reference to class template instantiation 'rd::WiredRdTask<TRes,ResSer>' being compiled
  WiredRdTaskImpl.h(66): [C4250] 'rd::detail::WiredRdTaskImpl<T,S>': inherits 'rd::RdBindableBase::rd::RdBindableBase::get_serialization_context' via dominance
  RdBindableBase.h(51): [C4250] see declaration of 'rd::RdBindableBase::get_serialization_context'
  WiredRdTaskImpl.h(66): [C4250] 'rd::detail::WiredRdTaskImpl<T,S>': inherits 'rd::RdBindableBase::rd::RdBindableBase::bind' via dominance
  RdBindableBase.h(47): [C4250] see declaration of 'rd::RdBindableBase::bind'
  WiredRdTaskImpl.h(66): [C4250] 'rd::detail::WiredRdTaskImpl<T,S>': inherits 'rd::RdBindableBase::rd::RdBindableBase::identify' via dominance
  RdBindableBase.h(49): [C4250] see declaration of 'rd::RdBindableBase::identify'
  Microsoft.MakeFile.targets(44, 5): [MSB3073] The command ""C:\Program Files\Epic Games\UE_5.2\Engine\Build\BatchFiles\Build.bat" TamedEditor Win64 Development -Project="C:\Users\SKIKK\Documents\Unreal Projects\Tamed-UE5\Tamed.uproject" -WaitMutex -FromMsBuild" exited with code 6.

**Comment by DecoyRS** [comment]
It was fixed in the 2023.2 build, you can try taking the latest Rider EAP build for it

**Comment by seb-exiin** [comment]
Indeed I can compile now, thanks

**Comment by WxKnight** [comment]
> It was fixed in the 2023.2 build, you can try taking the latest Rider EAP build for it


Hello, I am a developer. Because plugin emmyLua cannot work in rider 2023, can you fix it for 2022 as well? I'm currently encountering a similar problem

**Comment by WxKnight** [comment]
UBT-UnrealEditor-Win64-Development.txt 

Succeed launching fbuild process with ExitCode=-1
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger) in UnrealBuildTool\System\ActionGraph.cs:line 394
   at UnrealBuildTool.BuildMode.Build(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in UnrealBuildTool\Modes\BuildMode.cs:line 685
   at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in \UnrealBuildTool\Modes\BuildMode.cs:line 330
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments, ILogger Logger) in \UnrealBuildTool\Modes\BuildMode.cs:line 267
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in UnrealBuildTool.cs:line 719
WriteFileIfChanged() wrote 81 changed files of 8987 requested writes.

**Comment by DecoyRS** [comment]
Hello @WxKnight 
Sorry, but looks like your issue is not related to the RiderLink compilation by itself. Can you create a separate ticket and provide some more information like compilation error? That would be really helpfull
