### ISSUE TITLE
Riderlink cannot be installed into 5.3 UE project

### ISSUE THREAD

**Issue by astradamus** [JetBrains/UnrealLink#269]
This is super barebones and easy to reproduce:

1) Create new FPS template, C++ project in UE 5.3
2) Open the project in rider.
3) When prompted by Rider to add Riderlink, select Add to Editor.
4) Process begins, gets almost to 79/79, then fails at the very end. Every time no matter what I do.

As you can see there's pretty much no room for me to configure or do anything differently here. I'm guessing that Riderlink simply isn't updated for 5.3 yet, which is only a week old from what I can tell.

Here is what it says at the end of the build script terminal output:

```
BUILD FAILED
Failed to build RiderLink plugin for G:\UE_5.3
Failed to build RiderLink plugin
```

Just above that it gives a path to a log file. The log file is attached in full below, but I scanned it for pertinent details and I think this is the key error:

```
C:\Users\neuro\AppData\Local\Temp\UnrealLink\Coqelaz\HostProject\Plugins\RiderLink\Source\RiderGameControl\Private\RiderGameControl.cpp(20): fatal error C1083: Cannot open include file: 'UnrealEd/Public/Editor.h': No such file or directory
```

However, that file DOES seem to exist. I can locate it in rider, it is in "G:\UE_5.3\Engine\Source\Editor\UnrealEd\Public\Editor.h"

Any ideas?

[UBT-UnrealEditor-Win64-Development.txt](https://github.com/JetBrains/UnrealLink/files/12600734/UBT-UnrealEditor-Win64-Development.txt)

**Comment by astradamus** [comment]
To clarify I have tried everything short of using a different editor version. Reboots, reinstalls, nothing seems to solve this problem.

**Comment by astradamus** [comment]
I neglected to mention Rider version. There's some other info in here too, maybe it's useful 🤷‍♂️

JetBrains Rider 2022.3.2
Build #RD-223.8617.53, built on January 25, 2023
Licensed to ***
You have a perpetual fallback license for this version.
Subscription is active until ***
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 16
Registry:
    ide.mac.bigsur.window.with.tabs.enabled=false
    debugger.show.values.use.inlays=false
    ide.new.project.model.index.case.sensitivity=true
    platform.projectModel.workspace.model.file.index=false
    ide.workspace.model.rbs.as.tree=false
    rdclient.asyncActions=false
    vcs.empty.toolwindow.show=false
    indexing.enable.entity.provider.based.indexing=false
    database.show.search.tab=false

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.3)
    com.jetbrains.fast.mouse.scroll (1.6.0)
    com.microsoft.vso.idea (1.162.1)

**Comment by astradamus** [comment]
Pack it up, boys!

> BUILD SUCCESSFUL

Rider 2023.2.1 worked fine.

**Comment by NadavSch** [comment]
> Pack it up, boys!
> 
> > BUILD SUCCESSFUL
> 
> Rider 2023.2.1 worked fine.

Hi, I'm having the same issue that you had, I'm working with Rider 2022.2.4 and I can't install RiderLink.
I tried to switch to Rider 2023.2.1 and now I can't open the project at all.

If I'm trying to open any C++ file through Unreal, I get this message: "No project was found to open the file in".
I also tried to switch to Rider 2023.2.0 or Rider 2023.2.2, but I got the same results.

Any advice?

**Comment by Me-Maped** [comment]
I have the same problem，my rider version is 2022.3.3，how can i do without update rider?

**Comment by DecoyRS** [comment]
Try
Ctrh+Shift+A
Extract RiderLink
Swap RD folder of RiderLink with https://github.com/JetBrains/UnrealLink/tree/0a24d30f1af7ff79672a6a5cf968740cc2a57a23/src/cpp/RiderLink/Source/RD

**Comment by Jmarinesq** [comment]
> Try Ctrh+Shift+A Extract RiderLink Swap RD folder of RiderLink with https://github.com/JetBrains/UnrealLink/tree/0a24d30f1af7ff79672a6a5cf968740cc2a57a23/src/cpp/RiderLink/Source/RD

Tried it with JetBrains Rider 2022.2.4, it doesn't work
Do we need to patch different source files ?

**Comment by TinyNMT** [comment]
> Try Ctrh+Shift+A Extract RiderLink Swap RD folder of RiderLink with https://github.com/JetBrains/UnrealLink/tree/0a24d30f1af7ff79672a6a5cf968740cc2a57a23/src/cpp/RiderLink/Source/RD

It actually worked. Thanks

**Comment by tyogautomo** [comment]
> Try Ctrh+Shift+A Extract RiderLink Swap RD folder of RiderLink with https://github.com/JetBrains/UnrealLink/tree/0a24d30f1af7ff79672a6a5cf968740cc2a57a23/src/cpp/RiderLink/Source/RD

what is Ctlr+Shift+A actually do? where should I do the `Ctrl+Shift+A` ???

**Comment by P0stMelone** [comment]
> Try Ctrh+Shift+A Extract RiderLink Swap RD folder of RiderLink with https://github.com/JetBrains/UnrealLink/tree/0a24d30f1af7ff79672a6a5cf968740cc2a57a23/src/cpp/RiderLink/Source/RD

I did not understand where i've to insert the github link :(

**Comment by samirm** [comment]
same issue, UE 5.4.4 and Rider 2024.2.4
