### ISSUE TITLE
HighLight doesn't work

### ISSUE THREAD

**Issue by WebroLam** [JetBrains/UnrealLink#27]
“Usage of element at caret" doesn't work.
In fact, I also encountered this problem when using Resharper plugin in vs2017.
![image](https://user-images.githubusercontent.com/43696936/84126902-19da8880-aa71-11ea-9749-869509cfa52d.png)

I make sure it is turned on, but it still does not work.
![image](https://user-images.githubusercontent.com/43696936/84126267-44781180-aa70-11ea-9086-a66c4d8816e6.png)

The following figure is the color setting.
![image](https://user-images.githubusercontent.com/43696936/84127146-72aa2100-aa71-11ea-815a-b9e6e7363d1b.png)

Looking forward to your reply~! Thank!

**Comment by DecoyRS** [comment]
Hi @WebroLam!
Looks like it's the same issue as in: https://youtrack.jetbrains.com/issue/RSCPP-18514
I don't know if Rider team will add it to the next patch, but it will most certainly be available in 202 version.

**Comment by WebroLam** [comment]
@DecoyRS 
Thanks for your reply. I think I know where to go to find the answer.
