### ISSUE TITLE
Failed to build RiderLink plugin

### ISSUE THREAD

**Issue by Fadarve** [JetBrains/UnrealLink#273]
Hello, i keep having this error when i try to install RiderLink in the engine, im using Rider 2023.3.1 and UE 5.1.1, i've seen in other posts it had something to do with the registers but i already checked them and the "IntalledDirectory" is correctly set, i don't know what else to try. 

![image](https://github.com/JetBrains/UnrealLink/assets/50089110/f20bf98e-ef25-48fb-9a57-77b6f1e4c5f2)
![image](https://github.com/JetBrains/UnrealLink/assets/50089110/e0704b55-8a15-4941-87a8-392e5f4fc7a2)

**Comment by Fadarve** [comment]
Already solved, it has to do with not supporting not ascii characters on the folders, given that my windows username has an accent i had to change the riderlink installation intermediate folder, it is solved in #52

**Comment by DecoyRS** [comment]
One day I'll finally start detecting this issue during installation process and suggesting the fix... One day...
