### ISSUE TITLE
fatal error C1001: Internal compiler error.

### ISSUE THREAD

**Issue by Deooed** [JetBrains/UnrealLink#274]
[9/83] Compile [x64] LifetimeDefinition.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\INCLUDE\deque(349) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information

**Comment by DecoyRS** [comment]
That a pretty common crash for VC++ compiler, that usually means that you are out of RAM during the compilation of the project (or your swap is full). Double check that you have free space on disk C: and check if the issue persists.
