### ISSUE TITLE
Add filters to Unreal log

### ISSUE THREAD

**Issue by AJIADb9** [JetBrains/UnrealLink#3]
Add filter to Unreal log with searching by log types (find log category in UE4 now is hell)
![image](https://user-images.githubusercontent.com/8657156/79760695-1ce6b180-8329-11ea-877c-96f967f7c5d6.png)

**Comment by DecoyRS** [comment]
Added in UnrealLink [2020.2.61](https://github.com/JetBrains/UnrealLink/releases/tag/v2020.2.61)
Available in R4UE 2020.2.1
