### ISSUE TITLE
Can't package project while Unreal Link plugin is enabled

### ISSUE THREAD

**Issue by romanmaksy** [JetBrains/UnrealLink#32]
I've been trying out Rider for UE4 recently - mostly been smooth sailing however I get a cook error while trying to package the project while Rider is open if I have the Unreal Link plugin enabled (Win64 and Android, haven't tried other platforms).

Using the bundled 2020.1.10 version of the plugin that comes with Rider for Unreal Engine 2020.1.3, here are the before/after logs from attempting to package for Win64 with the plugin enabled/disabled if that helps!

[RiderLinkLogs.zip](https://github.com/JetBrains/UnrealLink/files/4908082/RiderLinkLogs.zip)

**Comment by DecoyRS** [comment]
Hi @romanmaksy !
This is due to RiderLink plugin being loaded in commandlet mode when cooking is being fired up.
This is fixed in latest RiderLink version, but it's not compatible with current release of "Rider for Unreal Engine".
As a fix you change module types in "RiderLink.uplugin" file to `EditorNoCommandlet`:
```
	"Modules": [
		{
			"Name": "RiderLink",
			"Type": "EditorNoCommandlet",
			"LoadingPhase": "PreDefault",
			"WhitelistPlatforms": [ "Win64" ]
		},
		{
			"Name": "RiderLoggingExtension",
			"Type": "EditorNoCommandlet",
			"LoadingPhase": "PreDefault",
			"WhitelistPlatforms": [ "Win64" ]
		},
		{
			"Name": "RiderBlueprintExtension",
			"Type": "EditorNoCommandlet",
			"LoadingPhase": "Default",
			"WhitelistPlatforms": [ "Win64" ]
		},
		{
			"Name": "RiderGameControlExtension",
			"Type": "EditorNoCommandlet",
			"LoadingPhase": "Default",
			"WhitelistPlatforms": [ "Win64" ]
		}
	]
```

**Comment by romanmaksy** [comment]
That seems to have done the trick, thanks!
