### ISSUE TITLE
Failure to define WIN32_LEAN_AND_MEAN in multiple locations

### ISSUE THREAD

**Issue by jaynus** [JetBrains/UnrealLink#33]
Multiple sources in the Unreal engine version lack the WIN32_LEAN_AND_MEAN  definitions needed to compile properly. 

I didn't test extensively, but to get it to compile you need to add it to:

`format-inl.h`
`windows_include.h`
`tcp_client-windows.h`

And to make sure to complete this in both 2017 and 2019 sources

**Comment by yvvan** [comment]
I guess we can add it to PublicDefinitions in RD.Build.cs but we need to check how it interacts with different versions first.
With which UE version does it not compile for you?

**Comment by Skittlebrau** [comment]
We had the same problem (Unreal 4.24 and 4.25).  I hacked up my copy of the plugin I got with Rider to have WIN32_LEAN_AND_MEAN defined and it fixed the issue.  I added it to all projects but didn't check if they all really needed it or not.

**Comment by DecoyRS** [comment]
@jaynus @Skittlebrau
Is Unity build enabled or disabled for your projects?
Will it work if you add this define in RD.Build.cs file, like
`PublicDefinitions.Add("WIN32_LEAN_AND_MEAN");`?

**Comment by Skittlebrau** [comment]
I do have Unity build enabled, however other people on our team do not and have the same issue.  I added the line you have there to *.Build.cs and it worked.  I know some of the other projects needed it (RiderLoggingExtension for example).  I didn't feel like trying to find the minimal set, so I just did it everywhere.

**Comment by DecoyRS** [comment]
Usually *disabling* Unity build might lead to some troubles building RiderLink plugin, but not being able to build a plugin when Unity build is *enabled* is a new one.

**Comment by Skittlebrau** [comment]
Adding to just RD.Build.cs does seem to be sufficient.
