### ISSUE TITLE
Editor freezing when using Search Everywhere [Double Shift]

### ISSUE THREAD

**Issue by lucasstern** [JetBrains/UnrealLink#35]
Since the last version, I'm having this issue that sometimes when pressing Double Shift to open the “Search Everywhere” popup search bar and starting typing, the editor will just freeze. But with no “not responding” status on the Task Manager.

I'm only able to open Rider again after force killing “rider64.exe” process.

I don't know if this will help, but I have some logs that looks related to the issue:
[threadDumps-freeze-20200717-233850-RDCPPP-202.5958.481.zip](https://github.com/JetBrains/UnrealLink/files/4940983/threadDumps-freeze-20200717-233850-RDCPPP-202.5958.481.zip)

My Specs:
![Screenshot637306374149537462](https://user-images.githubusercontent.com/20838771/87843164-89ba0b00-c888-11ea-8ed1-76c8bf17216f.png)

**Comment by DecoyRS** [comment]
Hi @lucasstern 
This looks like a more general issue for Rider for Unreal Engine.
I went ahead and created ticket in our task tracking system: https://youtrack.jetbrains.com/issue/RIDER-47906
All further investigation will be provided in that ticket
