### ISSUE TITLE
4.25.2 Is Not Compatible With RiderLink

### ISSUE THREAD

**Issue by dyanikoglu** [JetBrains/UnrealLink#38]
```
  Expecting to find a type to be declared in a module rules named 'RiderLink' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
```

With yesterday's 4.25.2 update, projects stopped compiling with RiderLink enabled in plugin list. (RiderLink is installed in engine)

**Comment by DecoyRS** [comment]
Hello @dyanikoglu 
This is a common bug in Unreal Engine 4.25.2 - even plugins from Marketplace won't work, if you place them in the Engine.
Please, use option "Install plugin in the Game" from `File | Settings | Languages & Frameworks | Unreal Engine` or disable RiderLink untill Epic Games would fix it.
Epic Games ticket: https://issues.unrealengine.com/issue/UE-95865
Cheers!

**Comment by dyanikoglu** [comment]
Thanks for the quick reply, looks like they will push a hotfix very soon. https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1755531-unreal-engine-4-25-released/page20#post1791825
