### ISSUE TITLE
RiderLink does not work in UE 4.25.2

### ISSUE THREAD

**Issue by kyangEPS** [JetBrains/UnrealLink#39]
I've been using Rider for Unreal Engine with version `4.25.1` perfectly fine, but after upgrading to `4.25.2` I'm getting this error when I try to build a project:
`Expecting to find a type to be declared in a module rules named 'RiderLink' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.`

In addition to this, I can't open Unreal Projects anymore because the engine doesn't recognize the installed version of Rider.

**Comment by DecoyRS** [comment]
Hello @kyangEPS 
This is a common bug in Unreal Engine 4.25.2 - even plugins from Marketplace won't work, if you place them in the Engine.
Please, use option "Install plugin in the Game" from File | Settings | Languages & Frameworks | Unreal Engine or disable RiderLink untill Epic Games would fix it.
Epic Games ticket: https://issues.unrealengine.com/issue/UE-95865
Cheers!

**Comment by DustMi** [comment]
I can confirm that the problem was resolved for me by installing Unreal 4.25.3

**Comment by kyangEPS** [comment]
just got the update too 👍 We're all good now!
