### ISSUE TITLE
Crash in RiderLink when packaging project

### ISSUE THREAD

**Issue by DecoyRS** [JetBrains/UnrealLink#4]
![image](https://user-images.githubusercontent.com/1694911/79982697-67923600-84af-11ea-9687-c93802929580.png)

**Comment by yvvan** [comment]
How did you reproduce that? Note that FSlateApplication::Get() should be called in specific thread so we can't get it right where we need it.

**Comment by sammalt** [comment]
Temp workaround. Modify FRiderLinkModule::StartupModule:

`
// Workaround begins:
if (!FSlateApplication::IsInitialized())
{
  return;
}
// Workaround ends.
  
rdConnection.init();
slateApplication = &FSlateApplication::Get();`
