### ISSUE TITLE
Failed to build RiderLink with cyrillic username

### ISSUE THREAD

**Issue by microneo** [JetBrains/UnrealLink#52]
Hi, 
I get RiderLink error both in editor and project.
After examining the logs, I found the following errors:

```
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users\ђ-ђ?‘?ђш‘?ђ?\AppData\Local\Temp\UnrealLink\Nihyhog\HostProject\Intermediate\Build\Win64\UE4Editor\Development\Core\SharedPCH.Core.RTTI.ShadowErrors.h.pch': No such file or directory
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users\ђ-ђ?‘?ђш‘?ђ?\AppData\Local\Temp\UnrealLink\Nihyhog\HostProject\Intermediate\Build\Win64\UE4Editor\Development\UnrealEd\SharedPCH.UnrealEd.RTTI.ShadowErrors.h.pch': No such file or directory
```

I can build riderlink manually using UAT command:
`{EngineRoot}/Engine/Build/BatchFiles/RunUAT.bat BuildPlugin -Plugin="C:/RiderLink/RiderLink.uplugin" -Package="C:/RiderLinkBuild" -Rocket`

Rider: D:\Programs\Rider for Unreal Engine 2020.2.1
Unreal Engine: D:\Programs\UE_4.25
Project: Q:\Projects\MyProject (blank project with empty c++ class)
User: C:\Users\Эдуард

[backend-err.log](https://github.com/JetBrains/UnrealLink/files/5313166/backend-err.log)
[idea.log](https://github.com/JetBrains/UnrealLink/files/5313167/idea.log)
[backend.log](https://github.com/JetBrains/UnrealLink/files/5313168/backend.log)

**Comment by DecoyRS** [comment]
Hi @microneo !
Can you test one thing - move these *.h.pch files to some temp directory and try installing RiderLink again, please.

**Comment by microneo** [comment]
I checked the directory, these files are missing. I didn't notice it. 

But there were these files:
```
Core\SharedPCH.Core.RTTI.ShadowErrors.h.pch.response
UnrealEd\SharedPCH.UnrealEd.RTTI.ShadowErrors.h.pch.response
```

I moved this files and try installing plugin, result was the same.

**Comment by tiagomagalhaes** [comment]
Having same problem since my home is at "C:\Users\TiagoMagalhães\".

Took a peek at the plugin compilation logs and there's a bunch of line with this pattern:
"c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users\TiagoMagalhAœes\AppData\Local\Temp\UnrealLink\Karuqaw\HostProject\Intermediate\Build\Win64\UE4Editor\Development\Core\SharedPCH.Core.RTTI.ShadowErrors.h.pch': No such file or directory"

"TiagoMagalhAœes" is not an HTML encoding problem, it's how it shows up in the log.

Do you want the full logs?

**Comment by DecoyRS** [comment]
Sorry for taking inappropriate amount of time getting back to this issue.
Issue boiled down to a cl-filter.exe utility from Epic Games that doesn't support non-ascii symbols, and we're working on a workaround.
Meanwhile, you can:
* Find RiderLink.zip under Rider installation folder;
* Unzip it into {Game}/Plugins/Developer/RiderLink
* Build your game

**Comment by DecoyRS** [comment]
There hasn't been updates to this issue, so I'll close it at this point.
Plus, now we have 2 options to build RiderLink when there are non-ASCII symbols in user's name:
* Use action "Extract RiderLink in Game without compiling", it'll simply extract RiderLink into your project, w/o building it
* Change `File | Settings | Languages & Frameworks | Unreal Engine | Intermediate folder to build RiderLink` to a folder that you have write access to and that doesn't have non-ASCII symbols
