### ISSUE TITLE
unresolved external symbols - Failed to build RiderLink plugin

### ISSUE THREAD

**Issue by lpestl** [JetBrains/UnrealLink#58]
I have a plugin build error in Rider. I have had it for a long time.
My environment:
* Windows 10 Enterprise (Version 1909) x64 
* Visual Studio 2019 Professional (v16.7.7) with toolchain **MSVC 14.16.27023** (I removed the toolchain MSVC 14.27.29110)
* Rider for Unreal Engine 2020.2.2 - Build #RDCPPP-202.7319.8, built on September 30, 2020

The build of the game is going fine. The game starts up. The following things are written in the logs of the build process (I don’t know if this information will be useful):
```
MSBuild version = "16.7.0+b89cb5fde"
...
WindowsSDK - 10.0.18362.0
```
When I try to install RiderLink plugin writes the following to the  event log:
```
16:24	Failed to build RiderLink plugin
			Failed to build plugin for E:\Source\gitpluginrun\GitPluginRun.uproject
			spdlog.lib(async.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    rd_core_cpp.lib(SequentialLifetimes.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    spdlog.lib(fmt.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    spdlog.lib(spdlog.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    spdlog.lib(color_sinks.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    rd_core_cpp.lib(to_string.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    rd_core_cpp.lib(LifetimeImpl.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    rd_core_cpp.lib(Lifetime.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    rd_core_cpp.lib(LifetimeDefinition.cpp.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4
			    r... (show balloon)

16:24	Failed to build RiderLink plugin
			Check build logs for more info
			Help > Diagnostic Tools > Show Log in Explorer
			And contact dev team for help at GitHub Issues page
```

**Comment by DecoyRS** [comment]
Hello @lpestl !
What version of UnrealLink plugin do you have installed right now?
The problem that you get is - one of the builds of bundled RiderLink plugin has external RD lib built with one of the latest versions of MSVC toolchain that has broke backward compatibility e.g. libs built with *new* toolchain can't by *older* toolchain..
As a solution, we've started to bundled RD lib built with older version of MSVC toolchain. You can either manually replace it in Rider installation, or later this week we'll have a new version of R4UE released.

**Comment by lpestl** [comment]
Hello, @DecoyRS !
Unreal Link - 2020.2.83
on Friday I also updated the Visual studio. Now it`s 16.8.1. 
I uninstalled the automatically installed with update toolchain version 14.28.29333 again. Left only 14.16.27023.
I will try to build RD with the older version of MSVC. But I also hope for your soon update!

**Comment by aviadmini** [comment]
Had the same issue. Solved by using latest RiderLink.zip from releases (not the whole UnrealLink, just the RiderLink)

**Comment by lpestl** [comment]
Cool! With the update, everything was fixed! Thanks! close this issue
