### ISSUE TITLE
Failed to Install RiderLink Plugin 

### ISSUE THREAD

**Issue by Corysia** [JetBrains/UnrealLink#63]
Uninstalled Rider for Unreal Engine 2020.2.2
Removed AppData/Local/JetBrains and AppData/Roaming/JetBrains folders
Removed Program Files/JetBrains

Fresh, clean install of Rider for Unreal 2020.3

Upgraded to UnrealLink 2020.3.116
Restarted Rider
Created a brand new C++ project in Unreal 4.25.4 (Epic)

RiderLink fails to install to Engine

Attached entire log directory
[log.zip](https://github.com/JetBrains/UnrealLink/files/5605381/log.zip)

**Comment by luckscx** [comment]
have the same probleam here. With unreal 4.24.
was success install UnrealLink on 2020.2.2. 
But failed on 2020.3

**Comment by DecoyRS** [comment]
Hello @Corysia @luckscx !
Would you be so kind to:
1. backup old RiderLink folder
2. Find {Rider_Install_Location}\plugins\UnrealLink\EditorPlugin\RiderLink.zip
3. Unzip it in place of old Rider
or
3. Unzip it in {Game_Project}\Plugins\RiderLink
4. Rebuild your game project
And share your results, please!

**Comment by Corysia** [comment]
I was not able to add it to the Engine.  It wanted me to recompile from source, which isn't something I'm set up to do right now.
I tried adding it to my Game by creating <Project>/Plugins/RiderLink.  Upon opening the project, it wanted to recompile.  That went fine.
Opening Rider, it again complains I don't have RiderLink installed.  I checked my plugins, it is not listed.  I tried to install to Game and again it failed.

**Comment by Shogo175R** [comment]
i ha the same issue, just i fixed it by delete the entire folder then reopen rider and make a new install of it.

**Comment by Corysia** [comment]
I've tried deleting everything...  Uninstalling Unreal, uninstalling Rider.  Combing thru AppData/Local and AppData/Roaming and removing anything related to Epic and JetBrains.  Reinstalled Unreal.  Created a new, blank C++ project in Unreal 4.25.4.  Installed Rider.  Pointed Unreal at Rider.  Built Rider project files.  Opened Rider.  Prompted to install Plugin.  And the same error.

At this point, if I could downgrade, I would.

**Comment by DecoyRS** [comment]
> I tried adding it to my Game by creating <Project>/Plugins/RiderLink. Upon opening the project in Unreal, it wanted to recompile. That went fine.

Refresh project files for game project after that. Either from Unreal Edtior, or from context menu of .uproject file.
Rider can't find installed RiderLink because there's no info about the plugins in project files.

As for "why Rider couldn't install RiderLink itself" - there should have been a popup after failed installation with these lines:
```
C:/Epic/UE_4.25/Engine/Plugins/Marketplace/Debug/Source/Debug/Public/DebugLogLibrarySettings.h(77) : LogUObjectHash: Error: Ambiguous path search, could be Enum /Script/DebugTools.EDebugLogType or Enum /Script/Debug.EDebugLogType
  C:/Epic/UE_4.25/Engine/Plugins/Marketplace/OWIEnhancedVehicleMovement/Source/OWIEnhancedVehicleMovement/Public/OWIVehicleMovementComponent.h(63) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
```
When installinig plugin, Rider uses [guidlines from Epic Games Store marketplace](https://www.unrealengine.com/en-US/marketplace-guidelines#263), they might be more strict than your locally setup rules for game project, but they guarantee that this plugin will work inside Unreal Engine after installation.

**Comment by ahrenm** [comment]
I think something is busted with the plugin.
The RD.Build.cs is referencing an include directory, which doesn't exist:

**C:\Data\Projects\Unreal\DayDream1\Plugins\Developer\RiderLink\Source\RD\RD.Build.cs: warning: Referenced directory 'C:\Data\Projects\Unreal\DayDream1\Plugins\Developer\RiderLink\Source\RD\include' does not exist.**

There is no "include" directory in the source tree under RD.
Everything under that fails to compile.

I'm going back to .83
That seems to compile ok

**Comment by DecoyRS** [comment]
@ahrenm have you tried backuping old version of RiderLink and installing it afresh?
Looks like there's a bug in "update plugin" pipeline that I'm investigating.

**Comment by ahrenm** [comment]
Yup.
A clean install of .83 works. I think I tried 113 and that was also not compiling.

**Comment by Corysia** [comment]
> > I tried adding it to my Game by creating /Plugins/RiderLink. Upon opening the project in Unreal, it wanted to recompile. That went fine.
> 
> Refresh project files for game project after that. Either from Unreal Edtior, or from context menu of .uproject file.
> Rider can't find installed RiderLink because there's no info about the plugins in project files.
> 
> As for "why Rider couldn't install RiderLink itself", you've got problems with locally installed plugin named `Debug`, there should have been a popup inside Rider after failed installation of RiderLink with these lines:
> 
> ```
> C:/Epic/UE_4.25/Engine/Plugins/Marketplace/Debug/Source/Debug/Public/DebugLogLibrarySettings.h(77) : LogUObjectHash: Error: Ambiguous path search, could be Enum /Script/DebugTools.EDebugLogType or Enum /Script/Debug.EDebugLogType
>   C:/Epic/UE_4.25/Engine/Plugins/Marketplace/OWIEnhancedVehicleMovement/Source/OWIEnhancedVehicleMovement/Public/OWIVehicleMovementComponent.h(63) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
> ```
> 
> When installinig plugin, Rider uses [guidlines from Epic Games Store marketplace](https://www.unrealengine.com/en-US/marketplace-guidelines#263), they might be more strict than your locally setup rules for game project, but they guarantee that this plugin will work inside Unreal Engine after installation.

Wow, you were absolutely right.  Removing that plugin resolved this.  That's unfortunate, since it's a plugin from the Unreal Marketplace, so I assumed it would have followed the guidelines.  Thanks so much for finding that.  I'm embarrassed now!
