### ISSUE TITLE
Failed to build Rider Link after upgrading from 2020.2 to 2020.3.1

### ISSUE THREAD

**Issue by Ikreb1** [JetBrains/UnrealLink#64]
[idea.log](https://github.com/JetBrains/UnrealLink/files/5607545/idea.log)
RiderLink plugin synchronization is required
			The RiderLink Unreal Editor plugin is not in sync with UnrealLink Rider plugin. Different versions of plugins are not guaranteed to work together.
			Installed version:	'2020.2.83'
			Required version:	'2020.3.116'

**Comment by DecoyRS** [comment]
Hello @Ikreb1 !
Would you be so kind to share other files from your log folder?

**Comment by Ikreb1** [comment]
[backend-err.log](https://github.com/JetBrains/UnrealLink/files/5608580/backend-err.log)
[backend-out.log](https://github.com/JetBrains/UnrealLink/files/5608581/backend-out.log)
[backend-protocol.log](https://github.com/JetBrains/UnrealLink/files/5608582/backend-protocol.log)
[frontend.log](https://github.com/JetBrains/UnrealLink/files/5608583/frontend.log)

I did install in game and not engine if that helps at all

**Comment by DecoyRS** [comment]
Hello @Ikreb1  !
Would you be so kind to:
1. backup old RiderLink folder
2. Find {Rider_Install_Location}\plugins\UnrealLink\EditorPlugin\RiderLink.zip
3. Unzip it in place of old Rider
or
3. Unzip it in {Game_Project}\Plugins\RiderLink
4. Rebuild your game project
And share your results, please!

**Comment by Ikreb1** [comment]
*Logs after following steps*
[backend.log](https://github.com/JetBrains/UnrealLink/files/5622140/backend.log)
[backend-err.log](https://github.com/JetBrains/UnrealLink/files/5622141/backend-err.log)
[backend-out.log](https://github.com/JetBrains/UnrealLink/files/5622142/backend-out.log)
[backend-protocol.log](https://github.com/JetBrains/UnrealLink/files/5622143/backend-protocol.log)
[frontend.log](https://github.com/JetBrains/UnrealLink/files/5622144/frontend.log)

Rider now tells me that RiderLink is required and that it can install in engine or game for me
It was in {Game_Project}\Plugins\**Developer**\RiderLink

then I moved it to {Game_Project}\Plugins\RiderLink
and it still says RiderLink plugin is required

Here are some more logs at the end if anything changed
[backend-protocol.log](https://github.com/JetBrains/UnrealLink/files/5622189/backend-protocol.log)
[frontend.log](https://github.com/JetBrains/UnrealLink/files/5622191/frontend.log)
[backend-out.log](https://github.com/JetBrains/UnrealLink/files/5622188/backend-out.log)
[backend-err.log](https://github.com/JetBrains/UnrealLink/files/5622187/backend-err.log)

Im just gonna install it in Game through rider and hope it works

**Comment by DecoyRS** [comment]
@Ikreb1 
oh, my bad, I've forgot about "Developer" subfolder. Move it to `{Game_Project}/Plugins/Developer/RiderLink` and everything should work after that.
