### ISSUE TITLE
Add option to install RiderLink to Engine instead of Game Project

### ISSUE THREAD

**Issue by DecoyRS** [JetBrains/UnrealLink#7]

**Comment by DecoyRS** [comment]
Official [doc from EpicGames](https://www.unrealengine.com/en-US/marketplace-guidelines#26) states, that
`Engine\Build\BatchFiles\RunUAT.bat BuildPlugin -Plugin=[Path to .uplugin file, must be outside engine directory] -Package=[Output directory] -Rocket` should build plugin, but it's not reliable (e.g. on UE 4.20 it's not working properly).
And Rocket Unreal Engine won't rebuild a plugin if you simply put a plugin in it's filestructure.
Until I've found a way to build a plugin from terminal in a stable manner, I won't be able to fix it(

**Comment by DecoyRS** [comment]
As a workaround, you can build RiderLink plugin in Game project and then move it to Engine project.
Rider checks if you have a plugin in Engine and won't install it to Game Projects

**Comment by dyanikoglu** [comment]
I just tried building engine from IDE with the RiderLink inside engine's plugins/developer folder. It built without any problem, and I was able to see the plugin in plugin list in my project. However, the plugin didn't work as expected, I couldn't see any log from the editor in Rider.

**Comment by DecoyRS** [comment]
@dyanikoglu I was talking about Engines from EGS. They won't build plugins, if you'd simply put it in their source code, you need to provide binaries.
As for the Engine from GitHub, it should be working alright as long as you put RiderLink plugin in the correct place e.g. {EngineRoot}/Engine/Plugins/Developer/RiderLink

**Comment by DecoyRS** [comment]
Fixed in v2020.1.8
