### ISSUE TITLE
Incorrect time in log

### ISSUE THREAD

**Issue by AJIADb9** [JetBrains/UnrealLink#8]
I'm currently in +3 GMT and it seems like it just adds extra 3 hours
![image](https://user-images.githubusercontent.com/8657156/80155548-98b35900-85ca-11ea-9c42-c945ce506d92.png)

**Comment by sammalt** [comment]
+1, in EEST, UTC+03:00 at the moment

**Comment by DecoyRS** [comment]
Fixed in v2020.1.7
