### ISSUE TITLE
Rider for Unreal 2021.1, "VersionName": "2021.1.7"

### ISSUE THREAD

**Issue by MrFish1968** [JetBrains/UnrealLink#93]
Rider is unable to build the plug-in, I just get...
"Failed to build Riderlink plugin"
This is with Unreal 4.26.1 and the errors are below, please note I have tried all the other options, including extracting the zip and building manually. I've stripped the full path from the beginning of the error messages.
  
**_HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(27): error C2143: syntax error: missing ';' before '<'

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(27): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(27): error C2238: unexpected token(s) preceding ';'
 
HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(28): error C2143: syntax error: missing ';' before '<'

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(28): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Public\RiderGameControlExtension.hpp(28): error C2238: unexpected token(s) preceding ';'

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Private\RiderGameControlExtension.cpp(484): error C2065: 'ActionsCache': undeclared identifier

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Private\RiderGameControlExtension.cpp(494): error C2065: 'GameControl': undeclared identifier

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Private\RiderGameControlExtension.cpp(495): error C2065: 'GameControl': undeclared identifier

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Private\RiderGameControlExtension.cpp(495): error C2065: 'ActionsCache': undeclared identifier

HostProject\Plugins\RiderLink\Source\RiderGameControlExtension\Private\RiderGameControlExtension.cpp(506): error C2065: 'ActionsCache': undeclared identifier_**

**Comment by ArtemiyAAA** [comment]
Hello, @MrFish1968 
Can you please open project, try to force install RiderLink by `File | Settings | Languages & Frameworks | Unreal Engine | Install RiderLink plugin` button and Report a Bug with attached logs by `Help->Report a Bug...`?

**Comment by MrFish1968** [comment]
You forgot to include the header for TUniquePtr...

#include "Templates/UniquePtr.h"

**Comment by DecoyRS** [comment]
Fixed in master, will be available in the next plugin release
